// kanken4-content.js — 原作の練習コンテンツバンク（漢検4級 出題範囲準拠）
//
// ここに収めた語・四字熟語・対義語/類義語・送り仮名・同音同訓異字・部首・
// 誤字訂正の各データは、すべて本モジュールのために書き起こした独自コンテンツで、
// 協会の過去問題文は一切複製していない（過去問の著作権は協会に帰属するため）。
// 用いる漢字はすべて4級までの配当（累計1339字）に収まることを、協会準拠のレベル表
// （mimneko/kanji-data 由来の「漢検漢字辞典」CSV）で機械的に検証済み。二字熟語の
// 読みはいずれも、各字の KANJIDIC 音訓読みへ連濁・促音を許して分解できることを
// 自動照合した（76語すべて成功）。同音・同訓異字と誤字訂正の選択肢は、正答以外が
// 文脈に当てはまらない（＝「誤答が実は正答」衝突を作らない）ことを人手で確認して
// いる。生成側（kanken4-generators.js）はこのデータから毎回問題を作る。
//
// 4級は9出題形式（読み／書取／部首・部首名／送り仮名／対義語・類義語／同音・同訓
// 異字／誤字訂正／四字熟語／熟語の構成）。3級には無い「誤字訂正」が本級で加わる。
const KANKEN4_CONTENT = {
  koseiLabels: {
    similar: '同じような意味の漢字を重ねたもの',
    opposite: '反対または対応の意味を表す字を重ねたもの',
    modifier: '上の字が下の字を修飾しているもの',
    object: '下の字が上の字の目的語・補語になっているもの',
    negation: '上の字が下の字の意味を打ち消しているもの',
  },
  words: [
    {w:'巨大', r:'きょだい', kosei:'similar'},
    {w:'恐怖', r:'きょうふ', kosei:'similar'},
    {w:'疲労', r:'ひろう', kosei:'similar'},
    {w:'巡回', r:'じゅんかい', kosei:'similar'},
    {w:'増殖', r:'ぞうしょく', kosei:'similar'},
    {w:'珍奇', r:'ちんき', kosei:'similar'},
    {w:'攻撃', r:'こうげき', kosei:'similar'},
    {w:'汚濁', r:'おだく', kosei:'similar'},
    {w:'悲惨', r:'ひさん', kosei:'similar'},
    {w:'皮膚', r:'ひふ', kosei:'similar'},
    {w:'継続', r:'けいぞく', kosei:'similar'},
    {w:'傾斜', r:'けいしゃ', kosei:'similar'},
    {w:'抵抗', r:'ていこう', kosei:'similar'},
    {w:'逃亡', r:'とうぼう', kosei:'similar'},
    {w:'腐敗', r:'ふはい', kosei:'similar'},
    {w:'乾燥', r:'かんそう', kosei:'similar'},
    {w:'脂肪', r:'しぼう', kosei:'similar'},
    {w:'祈願', r:'きがん', kosei:'similar'},
    {w:'添加', r:'てんか', kosei:'similar'},
    {w:'繁殖', r:'はんしょく', kosei:'similar'},
    {w:'恒久', r:'こうきゅう', kosei:'similar'},
    {w:'岩石', r:'がんせき', kosei:'similar'},
    {w:'絵画', r:'かいが', kosei:'similar'},
    {w:'河川', r:'かせん', kosei:'similar'},
    {w:'攻防', r:'こうぼう', kosei:'opposite'},
    {w:'濃淡', r:'のうたん', kosei:'opposite'},
    {w:'是非', r:'ぜひ', kosei:'opposite'},
    {w:'需給', r:'じゅきゅう', kosei:'opposite'},
    {w:'増減', r:'ぞうげん', kosei:'opposite'},
    {w:'往復', r:'おうふく', kosei:'opposite'},
    {w:'縦横', r:'じゅうおう', kosei:'opposite'},
    {w:'損得', r:'そんとく', kosei:'opposite'},
    {w:'濃霧', r:'のうむ', kosei:'modifier'},
    {w:'猛獣', r:'もうじゅう', kosei:'modifier'},
    {w:'珍味', r:'ちんみ', kosei:'modifier'},
    {w:'鋭角', r:'えいかく', kosei:'modifier'},
    {w:'荒野', r:'こうや', kosei:'modifier'},
    {w:'微量', r:'びりょう', kosei:'modifier'},
    {w:'恒星', r:'こうせい', kosei:'modifier'},
    {w:'秀作', r:'しゅうさく', kosei:'modifier'},
    {w:'稲作', r:'いなさく', kosei:'modifier'},
    {w:'砂丘', r:'さきゅう', kosei:'modifier'},
    {w:'舞台', r:'ぶたい', kosei:'modifier'},
    {w:'影絵', r:'かげえ', kosei:'modifier'},
    {w:'握手', r:'あくしゅ', kosei:'object'},
    {w:'拍手', r:'はくしゅ', kosei:'object'},
    {w:'避難', r:'ひなん', kosei:'object'},
    {w:'越境', r:'えっきょう', kosei:'object'},
    {w:'起訴', r:'きそ', kosei:'object'},
    {w:'求婚', r:'きゅうこん', kosei:'object'},
    {w:'脱帽', r:'だつぼう', kosei:'object'},
    {w:'非凡', r:'ひぼん', kosei:'negation'},
    {w:'未婚', r:'みこん', kosei:'negation'},
    {w:'無尽', r:'むじん', kosei:'negation'},
    {w:'未詳', r:'みしょう', kosei:'negation'},
    {w:'不惑', r:'ふわく', kosei:'negation'},
    {w:'非力', r:'ひりき', kosei:'negation'},
  ],
  pairs: [
    {a:'攻撃', ar:'こうげき', b:'防御', br:'ぼうぎょ', rel:'antonym'},
    {a:'濃厚', ar:'のうこう', b:'希薄', br:'きはく', rel:'antonym'},
    {a:'鋭利', ar:'えいり', b:'鈍重', br:'どんじゅう', rel:'antonym'},
    {a:'継続', ar:'けいぞく', b:'中断', br:'ちゅうだん', rel:'antonym'},
    {a:'歓喜', ar:'かんき', b:'悲嘆', br:'ひたん', rel:'antonym'},
    {a:'優良', ar:'ゆうりょう', b:'劣悪', br:'れつあく', rel:'antonym'},
    {a:'勝利', ar:'しょうり', b:'敗北', br:'はいぼく', rel:'antonym'},
    {a:'陽気', ar:'ようき', b:'陰気', br:'いんき', rel:'antonym'},
    {a:'拡大', ar:'かくだい', b:'縮小', br:'しゅくしょう', rel:'antonym'},
    {a:'賛成', ar:'さんせい', b:'反対', br:'はんたい', rel:'antonym'},
    {a:'永遠', ar:'えいえん', b:'恒久', br:'こうきゅう', rel:'synonym'},
    {a:'突然', ar:'とつぜん', b:'不意', br:'ふい', rel:'synonym'},
    {a:'祈願', ar:'きがん', b:'祈念', br:'きねん', rel:'synonym'},
    {a:'力作', ar:'りきさく', b:'秀作', br:'しゅうさく', rel:'synonym'},
    {a:'警戒', ar:'けいかい', b:'用心', br:'ようじん', rel:'synonym'},
    {a:'抜群', ar:'ばつぐん', b:'屈指', br:'くっし', rel:'synonym'},
    {a:'風潮', ar:'ふうちょう', b:'傾向', br:'けいこう', rel:'synonym'},
    {a:'歓迎', ar:'かんげい', b:'歓待', br:'かんたい', rel:'synonym'},
    {a:'冷静', ar:'れいせい', b:'沈着', br:'ちんちゃく', rel:'synonym'},
  ],
  yoji: [
    {w:'半信半疑', r:'はんしんはんぎ', gloss:'半分は信じ半分は疑うこと', blank:3, ans:'疑'},
    {w:'異口同音', r:'いくどうおん', gloss:'多くの人が口をそろえて同じことを言うこと', blank:2, ans:'同'},
    {w:'危機一髪', r:'ききいっぱつ', gloss:'あぶないせとぎわ', blank:3, ans:'髪'},
    {w:'自画自賛', r:'じがじさん', gloss:'自分で自分をほめること', blank:3, ans:'賛'},
    {w:'油断大敵', r:'ゆだんたいてき', gloss:'油断は失敗のもとで恐ろしいということ', blank:2, ans:'大'},
    {w:'温故知新', r:'おんこちしん', gloss:'古いことを学んで新しい知識を得ること', blank:0, ans:'温'},
    {w:'公明正大', r:'こうめいせいだい', gloss:'私心がなく公正なこと', blank:0, ans:'公'},
    {w:'針小棒大', r:'しんしょうぼうだい', gloss:'小さな事を大げさに言うこと', blank:2, ans:'棒'},
    {w:'意気投合', r:'いきとうごう', gloss:'たがいの気持ちがぴったり合うこと', blank:3, ans:'合'},
    {w:'一部始終', r:'いちぶしじゅう', gloss:'物事の始めから終わりまで全部', blank:3, ans:'終'},
    {w:'起死回生', r:'きしかいせい', gloss:'絶望的な状態を立て直すこと', blank:2, ans:'回'},
    {w:'空前絶後', r:'くうぜんぜつご', gloss:'過去にも将来にも例がないほど珍しいこと', blank:3, ans:'後'},
    {w:'無我夢中', r:'むがむちゅう', gloss:'我を忘れて物事に熱中すること', blank:2, ans:'夢'},
    {w:'大同小異', r:'だいどうしょうい', gloss:'細部は違うが大体は同じであること', blank:2, ans:'小'},
    {w:'平身低頭', r:'へいしんていとう', gloss:'ひたすらおそれいってわびること', blank:3, ans:'頭'},
    {w:'単純明快', r:'たんじゅんめいかい', gloss:'こみいっておらず分かりやすいこと', blank:2, ans:'明'},
    {w:'付和雷同', r:'ふわらいどう', gloss:'自分の考えなく人の意見に従うこと', blank:2, ans:'雷'},
    {w:'絶体絶命', r:'ぜったいぜつめい', gloss:'どうにも逃れられない苦しい立場', blank:2, ans:'絶'},
  ],
  okuri: [
    {r:'あやまる', stem:'誤', split:3, gloss:'まちがえる'},
    {r:'こころよい', stem:'快', split:4, gloss:'気持ちがよい'},
    {r:'うたがう', stem:'疑', split:3, gloss:'ほんとうかと思う'},
    {r:'おそれる', stem:'恐', split:2, gloss:'こわいと感じる'},
    {r:'かたむく', stem:'傾', split:3, gloss:'ななめになる'},
    {r:'きたない', stem:'汚', split:3, gloss:'よごれている'},
    {r:'さからう', stem:'逆', split:2, gloss:'反対の方へ向かう'},
    {r:'たくわえる', stem:'蓄', split:3, gloss:'ためておく'},
    {r:'つらなる', stem:'連', split:2, gloss:'ひと続きになる'},
    {r:'のがれる', stem:'逃', split:2, gloss:'にげる'},
    {r:'はげしい', stem:'激', split:2, gloss:'勢いが強い'},
    {r:'ひきいる', stem:'率', split:2, gloss:'人の先に立って導く'},
    {r:'まねく', stem:'招', split:2, gloss:'呼び寄せる'},
    {r:'みだれる', stem:'乱', split:2, gloss:'ばらばらになる'},
    {r:'もえる', stem:'燃', split:1, gloss:'火がつく'},
    {r:'やしなう', stem:'養', split:3, gloss:'そだてる'},
    {r:'あばれる', stem:'暴', split:2, gloss:'乱暴にふるまう'},
    {r:'こころみる', stem:'試', split:3, gloss:'ためしにやってみる'},
    {r:'すこやか', stem:'健', split:2, gloss:'元気で丈夫だ'},
    {r:'たしかめる', stem:'確', split:2, gloss:'まちがいないか調べる'},
    {r:'つとめる', stem:'努', split:2, gloss:'力をつくす'},
    {r:'みちびく', stem:'導', split:3, gloss:'案内して教える'},
  ],
  doon: [
    {read:'コウ', phrase:'敵の陣地を◯撃する', ans:'攻', dis:['抗','更','稿']},
    {read:'カン', phrase:'手の◯をふく', ans:'汗', dis:['甘','刊','乾']},
    {read:'ケイ', phrase:'斜面が◯斜している', ans:'傾', dis:['系','径','恵']},
    {read:'シン', phrase:'大きな地◯で家がゆれる', ans:'震', dis:['侵','慎','浸']},
    {read:'ヒ', phrase:'危険を回◯する', ans:'避', dis:['疲','被','彼']},
    {read:'カク', phrase:'獲物を捕◯する', ans:'獲', dis:['較','各','格']},
    {read:'チョウ', phrase:'高く◯躍する', ans:'跳', dis:['徴','調','張']},
    {read:'トウ', phrase:'敵と◯争する', ans:'闘', dis:['盗','逃','倒']},
    {read:'ハク', phrase:'船が港に停◯する', ans:'泊', dis:['迫','拍','薄']},
    {read:'フ', phrase:'木の葉が水面に◯遊する', ans:'浮', dis:['腐','普','敷']},
    {read:'ボウ', phrase:'危険を予◯する', ans:'防', dis:['忙','坊','傍']},
    {read:'ハン', phrase:'商品を◯売する', ans:'販', dis:['般','搬','範']},
    {read:'ソウ', phrase:'空気が乾◯する', ans:'燥', dis:['騒','僧','層']},
    {read:'エン', phrase:'困っている人を◯助する', ans:'援', dis:['煙','鉛','縁']},
  ],
  goji: [
    {sentence:'危険を回【被】する。', wrong:'被', ans:'避', dis:['疲','批','費'], read:'ヒ'},
    {sentence:'敵と激しく戦【盗】する。', wrong:'盗', ans:'闘', dis:['討','倒','逃'], read:'トウ'},
    {sentence:'作品の特【調】をとらえる。', wrong:'調', ans:'徴', dis:['張','朝','帳'], read:'チョウ'},
    {sentence:'【農】厚な味の料理を作る。', wrong:'農', ans:'濃', dis:['脳','悩','納'], read:'ノウ'},
    {sentence:'最近の流行の【継】向を調べる。', wrong:'継', ans:'傾', dis:['系','型','敬'], read:'ケイ'},
    {sentence:'洗濯物が乾【騒】する。', wrong:'騒', ans:'燥', dis:['操','層','総'], read:'ソウ'},
    {sentence:'駅前にビルを建【接】する。', wrong:'接', ans:'設', dis:['節','折','説'], read:'セツ'},
    {sentence:'先生のお宅を【方】問する。', wrong:'方', ans:'訪', dis:['放','防','包'], read:'ホウ'},
    {sentence:'計画を【証】認する。', wrong:'証', ans:'承', dis:['招','焼','章'], read:'ショウ'},
    {sentence:'市場を独【専】する。', wrong:'専', ans:'占', dis:['宣','鮮','泉'], read:'セン'},
    {sentence:'新商品を【般】売する。', wrong:'般', ans:'販', dis:['搬','範','版'], read:'ハン'},
    {sentence:'山で【帽】険をする。', wrong:'帽', ans:'冒', dis:['坊','傍','忙'], read:'ボウ'},
  ],
  bushu: [
    {k:'握', rad:'扌', name:'てへん'},
    {k:'影', rad:'彡', name:'さんづくり'},
    {k:'鋭', rad:'金', name:'かねへん'},
    {k:'煙', rad:'火', name:'ひへん'},
    {k:'汚', rad:'氵', name:'さんずい'},
    {k:'菓', rad:'艹', name:'くさかんむり'},
    {k:'雅', rad:'隹', name:'ふるとり'},
    {k:'環', rad:'王', name:'おうへん'},
    {k:'鑑', rad:'金', name:'かねへん'},
    {k:'祈', rad:'礻', name:'しめすへん'},
    {k:'鬼', rad:'鬼', name:'おに'},
    {k:'輝', rad:'車', name:'くるま'},
    {k:'御', rad:'彳', name:'ぎょうにんべん'},
    {k:'恒', rad:'忄', name:'りっしんべん'},
    {k:'稿', rad:'禾', name:'のぎへん'},
    {k:'婚', rad:'女', name:'おんなへん'},
    {k:'鎖', rad:'金', name:'かねへん'},
    {k:'彩', rad:'彡', name:'さんづくり'},
    {k:'惨', rad:'忄', name:'りっしんべん'},
    {k:'雌', rad:'隹', name:'ふるとり'},
    {k:'脂', rad:'月', name:'にくづき'},
    {k:'趣', rad:'走', name:'そうにょう'},
    {k:'襲', rad:'衣', name:'ころも'},
    {k:'盾', rad:'目', name:'め'},
    {k:'沼', rad:'氵', name:'さんずい'},
    {k:'触', rad:'角', name:'つのへん'},
    {k:'侵', rad:'亻', name:'にんべん'},
    {k:'陣', rad:'阝', name:'こざとへん'},
    {k:'尋', rad:'寸', name:'すん'},
    {k:'姓', rad:'女', name:'おんなへん'},
    {k:'扇', rad:'戸', name:'とだれ'},
    {k:'訴', rad:'言', name:'ごんべん'},
    {k:'燥', rad:'火', name:'ひへん'},
    {k:'騒', rad:'馬', name:'うまへん'},
    {k:'濁', rad:'氵', name:'さんずい'},
    {k:'嘆', rad:'口', name:'くちへん'},
    {k:'弾', rad:'弓', name:'ゆみへん'},
    {k:'抵', rad:'扌', name:'てへん'},
    {k:'殿', rad:'殳', name:'るまた'},
    {k:'闘', rad:'門', name:'もんがまえ'},
    {k:'胴', rad:'月', name:'にくづき'},
    {k:'峠', rad:'山', name:'やまへん'},
    {k:'曇', rad:'日', name:'ひ'},
    {k:'悩', rad:'忄', name:'りっしんべん'},
    {k:'杯', rad:'木', name:'きへん'},
    {k:'輩', rad:'車', name:'くるま'},
    {k:'販', rad:'貝', name:'かいへん'},
    {k:'搬', rad:'扌', name:'てへん'},
    {k:'繁', rad:'糸', name:'いと'},
    {k:'彼', rad:'彳', name:'ぎょうにんべん'},
    {k:'描', rad:'扌', name:'てへん'},
    {k:'浜', rad:'氵', name:'さんずい'},
    {k:'敷', rad:'攵', name:'ぼくづくり'},
    {k:'舞', rad:'舛', name:'まいあし'},
    {k:'噴', rad:'口', name:'くちへん'},
    {k:'捕', rad:'扌', name:'てへん'},
    {k:'抱', rad:'扌', name:'てへん'},
    {k:'砲', rad:'石', name:'いしへん'},
    {k:'傍', rad:'亻', name:'にんべん'},
    {k:'帽', rad:'巾', name:'はばへん'},
    {k:'慢', rad:'忄', name:'りっしんべん'},
    {k:'眠', rad:'目', name:'めへん'},
    {k:'霧', rad:'雨', name:'あめかんむり'},
    {k:'猛', rad:'犭', name:'けものへん'},
    {k:'網', rad:'糸', name:'いとへん'},
    {k:'躍', rad:'足', name:'あしへん'},
    {k:'謡', rad:'言', name:'ごんべん'},
    {k:'翼', rad:'羽', name:'はね'},
    {k:'絡', rad:'糸', name:'いとへん'},
    {k:'欄', rad:'木', name:'きへん'},
    {k:'離', rad:'隹', name:'ふるとり'},
    {k:'粒', rad:'米', name:'こめへん'},
    {k:'隣', rad:'阝', name:'こざとへん'},
    {k:'麗', rad:'鹿', name:'しか'},
    {k:'暦', rad:'日', name:'ひ'},
    {k:'恋', rad:'心', name:'こころ'},
    {k:'露', rad:'雨', name:'あめかんむり'},
    {k:'惑', rad:'心', name:'こころ'},
    {k:'腕', rad:'月', name:'にくづき'},
  ],
};
if (typeof module !== 'undefined') { module.exports = { KANKEN4_CONTENT }; }
