// vocab.js — New Horizon Elementary Picture Dictionary vocabulary
// ~500 words across 28 categories, with emoji hints and Japanese readings

'use strict';

const NH_CATEGORIES = [
  { id: 'feelings',       ja: '気持ち',         en: 'Feelings',          emoji: '😊', color: '#4A6B4F' },
  { id: 'numbers',        ja: '数',              en: 'Numbers',           emoji: '🔢', color: '#B5572E' },
  { id: 'colors',         ja: '色',              en: 'Colors',            emoji: '🎨', color: '#C9A24B' },
  { id: 'shapes',         ja: '形',              en: 'Shapes',            emoji: '🔷', color: '#6E8B3D' },
  { id: 'sports',         ja: 'スポーツ',         en: 'Sports',            emoji: '⚽', color: '#8C5A72' },
  { id: 'food',           ja: '食べ物',           en: 'Food',              emoji: '🍱', color: '#A8432A' },
  { id: 'drinks',         ja: '飲み物',           en: 'Drinks',            emoji: '🥤', color: '#3F7A6B' },
  { id: 'desserts',       ja: 'デザート',         en: 'Desserts',          emoji: '🍰', color: '#C06A2E' },
  { id: 'fruit',          ja: '果物',             en: 'Fruit',             emoji: '🍎', color: '#7A5A3C' },
  { id: 'vegetables',     ja: '野菜',             en: 'Vegetables',        emoji: '🥦', color: '#5B7A5E' },
  { id: 'ingredients',    ja: '食材',             en: 'Ingredients',       emoji: '🥩', color: '#9A7B2E' },
  { id: 'tastes',         ja: '味',              en: 'Tastes',            emoji: '😋', color: '#A85A3C' },
  { id: 'animals',        ja: '動物',             en: 'Animals',           emoji: '🐘', color: '#4A6B4F' },
  { id: 'sea-animals',    ja: '海の生き物',        en: 'Sea Animals',       emoji: '🐬', color: '#B5572E' },
  { id: 'bugs',           ja: '虫',              en: 'Bugs',              emoji: '🦋', color: '#C9A24B' },
  { id: 'nature',         ja: '自然',             en: 'Nature',            emoji: '🏔️', color: '#6E8B3D' },
  { id: 'time',           ja: '月・曜日・季節',    en: 'Time',              emoji: '📅', color: '#8C5A72' },
  { id: 'weather',        ja: '天気',             en: 'Weather',           emoji: '⛅', color: '#A8432A' },
  { id: 'people',         ja: '人',              en: 'People',            emoji: '👨‍👩‍👧', color: '#3F7A6B' },
  { id: 'family',         ja: '家族',             en: 'Family',            emoji: '👪', color: '#C06A2E' },
  { id: 'personalities',  ja: '性格',             en: 'Personalities',     emoji: '🌟', color: '#7A5A3C' },
  { id: 'actions',        ja: '動作',             en: 'Actions',           emoji: '🏃', color: '#5B7A5E' },
  { id: 'daily',          ja: '一日の生活',        en: 'Daily Activities',  emoji: '🌅', color: '#9A7B2E' },
  { id: 'clothes',        ja: '服装',             en: 'Clothes',           emoji: '👕', color: '#A85A3C' },
  { id: 'body',           ja: 'からだ',           en: 'Body',              emoji: '💪', color: '#4A6B4F' },
  { id: 'town',           ja: '町',              en: 'Town',              emoji: '🏘️', color: '#B5572E' },
  { id: 'school',         ja: '学校・教科',        en: 'School',            emoji: '🏫', color: '#C9A24B' },
  { id: 'stationery',     ja: '文房具',           en: 'Stationery',        emoji: '✏️', color: '#6E8B3D' },
  { id: 'instruments',    ja: '楽器',             en: 'Instruments',       emoji: '🎵', color: '#8C5A72' },
  { id: 'things',         ja: '身の回りのもの',    en: 'Everyday Things',   emoji: '🎒', color: '#A8432A' },
  { id: 'events',         ja: '学校行事・年中行事', en: 'Events',           emoji: '🎉', color: '#3F7A6B' },
  { id: 'descriptions',   ja: '様子・様子',        en: 'Descriptions',      emoji: '✨', color: '#C06A2E' },
  { id: 'jobs',           ja: '職業',             en: 'Jobs',              emoji: '👩‍⚕️', color: '#7A5A3C' },
  { id: 'clubs',          ja: '部活動',           en: 'Clubs & Teams',     emoji: '🏅', color: '#5B7A5E' },
];

// grade: 5 or 6 or 'both'. unit: unit number within grade. 0 = general.
const NH_VOCAB = [
  // ── FEELINGS ──────────────────────────────────────────────────────────────
  { id:'fe01', en:'happy',    ja:'うれしい',          emoji:'😊', cat:'feelings', grade:5, unit:1 },
  { id:'fe02', en:'sad',      ja:'かなしい',          emoji:'😢', cat:'feelings', grade:5, unit:1 },
  { id:'fe03', en:'fine',     ja:'元気',             emoji:'😄', cat:'feelings', grade:5, unit:1 },
  { id:'fe04', en:'good',     ja:'いい・よい',        emoji:'👍', cat:'feelings', grade:5, unit:1 },
  { id:'fe05', en:'great',    ja:'すごくいい',        emoji:'🤩', cat:'feelings', grade:5, unit:1 },
  { id:'fe06', en:'nervous',  ja:'きんちょうした',    emoji:'😰', cat:'feelings', grade:5, unit:1 },
  { id:'fe07', en:'hungry',   ja:'おなかがすいた',    emoji:'😤', cat:'feelings', grade:5, unit:1 },
  { id:'fe08', en:'thirsty',  ja:'のどがかわいた',    emoji:'🥵', cat:'feelings', grade:5, unit:1 },
  { id:'fe09', en:'tired',    ja:'つかれた',          emoji:'😩', cat:'feelings', grade:5, unit:1 },
  { id:'fe10', en:'sleepy',   ja:'ねむい',           emoji:'😴', cat:'feelings', grade:5, unit:1 },
  { id:'fe11', en:'busy',     ja:'いそがしい',        emoji:'😵', cat:'feelings', grade:5, unit:1 },

  // ── NUMBERS ───────────────────────────────────────────────────────────────
  { id:'nu01', en:'zero',       ja:'れい・ゼロ',   emoji:'0️⃣', cat:'numbers', grade:5, unit:1 },
  { id:'nu02', en:'one',        ja:'いち',        emoji:'1️⃣', cat:'numbers', grade:5, unit:1 },
  { id:'nu03', en:'two',        ja:'に',          emoji:'2️⃣', cat:'numbers', grade:5, unit:1 },
  { id:'nu04', en:'three',      ja:'さん',        emoji:'3️⃣', cat:'numbers', grade:5, unit:1 },
  { id:'nu05', en:'four',       ja:'し・よん',    emoji:'4️⃣', cat:'numbers', grade:5, unit:1 },
  { id:'nu06', en:'five',       ja:'ご',          emoji:'5️⃣', cat:'numbers', grade:5, unit:1 },
  { id:'nu07', en:'six',        ja:'ろく',        emoji:'6️⃣', cat:'numbers', grade:5, unit:1 },
  { id:'nu08', en:'seven',      ja:'しち・なな',  emoji:'7️⃣', cat:'numbers', grade:5, unit:1 },
  { id:'nu09', en:'eight',      ja:'はち',        emoji:'8️⃣', cat:'numbers', grade:5, unit:1 },
  { id:'nu10', en:'nine',       ja:'く・きゅう',  emoji:'9️⃣', cat:'numbers', grade:5, unit:1 },
  { id:'nu11', en:'ten',        ja:'じゅう',      emoji:'🔟', cat:'numbers', grade:5, unit:1 },
  { id:'nu12', en:'eleven',     ja:'じゅういち',  emoji:'🎯', cat:'numbers', grade:5, unit:1 },
  { id:'nu13', en:'twelve',     ja:'じゅうに',    emoji:'🎯', cat:'numbers', grade:5, unit:1 },
  { id:'nu14', en:'thirteen',   ja:'じゅうさん',  emoji:'🎯', cat:'numbers', grade:5, unit:1 },
  { id:'nu15', en:'fourteen',   ja:'じゅうし',    emoji:'🎯', cat:'numbers', grade:5, unit:1 },
  { id:'nu16', en:'fifteen',    ja:'じゅうご',    emoji:'🎯', cat:'numbers', grade:5, unit:1 },
  { id:'nu17', en:'sixteen',    ja:'じゅうろく',  emoji:'🎯', cat:'numbers', grade:5, unit:1 },
  { id:'nu18', en:'seventeen',  ja:'じゅうしち',  emoji:'🎯', cat:'numbers', grade:5, unit:1 },
  { id:'nu19', en:'eighteen',   ja:'じゅうはち',  emoji:'🎯', cat:'numbers', grade:5, unit:1 },
  { id:'nu20', en:'nineteen',   ja:'じゅうく',    emoji:'🎯', cat:'numbers', grade:5, unit:1 },
  { id:'nu21', en:'twenty',     ja:'にじゅう',    emoji:'🎯', cat:'numbers', grade:5, unit:1 },
  { id:'nu22', en:'thirty',     ja:'さんじゅう',  emoji:'🎯', cat:'numbers', grade:5, unit:1 },
  { id:'nu23', en:'forty',      ja:'よんじゅう',  emoji:'🎯', cat:'numbers', grade:5, unit:1 },
  { id:'nu24', en:'fifty',      ja:'ごじゅう',    emoji:'🎯', cat:'numbers', grade:5, unit:1 },
  { id:'nu25', en:'sixty',      ja:'ろくじゅう',  emoji:'🎯', cat:'numbers', grade:5, unit:1 },
  { id:'nu26', en:'seventy',    ja:'ななじゅう',  emoji:'🎯', cat:'numbers', grade:5, unit:1 },
  { id:'nu27', en:'eighty',     ja:'はちじゅう',  emoji:'🎯', cat:'numbers', grade:5, unit:1 },
  { id:'nu28', en:'ninety',     ja:'きゅうじゅう',emoji:'🎯', cat:'numbers', grade:5, unit:1 },
  { id:'nu29', en:'one hundred',ja:'ひゃく',      emoji:'💯', cat:'numbers', grade:5, unit:1 },

  // ── COLORS ────────────────────────────────────────────────────────────────
  { id:'co01', en:'white',        ja:'しろ',      emoji:'⬜', cat:'colors', grade:5, unit:1 },
  { id:'co02', en:'red',          ja:'あか',      emoji:'🔴', cat:'colors', grade:5, unit:1 },
  { id:'co03', en:'orange',       ja:'オレンジ',  emoji:'🟠', cat:'colors', grade:5, unit:1 },
  { id:'co04', en:'yellow',       ja:'きいろ',    emoji:'🟡', cat:'colors', grade:5, unit:1 },
  { id:'co05', en:'green',        ja:'みどり',    emoji:'🟢', cat:'colors', grade:5, unit:1 },
  { id:'co06', en:'light blue',   ja:'みずいろ',  emoji:'🩵', cat:'colors', grade:5, unit:1 },
  { id:'co07', en:'yellow green', ja:'きみどり',  emoji:'💚', cat:'colors', grade:5, unit:1 },
  { id:'co08', en:'gold',         ja:'きん',      emoji:'🥇', cat:'colors', grade:5, unit:1 },
  { id:'co09', en:'silver',       ja:'ぎん',      emoji:'🥈', cat:'colors', grade:5, unit:1 },
  { id:'co10', en:'blue',         ja:'あお',      emoji:'🔵', cat:'colors', grade:5, unit:1 },
  { id:'co11', en:'black',        ja:'くろ',      emoji:'⬛', cat:'colors', grade:5, unit:1 },
  { id:'co12', en:'brown',        ja:'ちゃいろ',  emoji:'🟫', cat:'colors', grade:5, unit:1 },
  { id:'co13', en:'purple',       ja:'むらさき',  emoji:'🟣', cat:'colors', grade:5, unit:1 },
  { id:'co14', en:'pink',         ja:'ピンク',    emoji:'🌸', cat:'colors', grade:5, unit:1 },

  // ── SHAPES ────────────────────────────────────────────────────────────────
  { id:'sh01', en:'circle',    ja:'まる・えん',    emoji:'⭕', cat:'shapes', grade:5, unit:1 },
  { id:'sh02', en:'square',    ja:'しかく',        emoji:'⬛', cat:'shapes', grade:5, unit:1 },
  { id:'sh03', en:'star',      ja:'ほし',          emoji:'⭐', cat:'shapes', grade:5, unit:1 },
  { id:'sh04', en:'cross',     ja:'じゅうじ',      emoji:'✚', cat:'shapes', grade:5, unit:1 },
  { id:'sh05', en:'triangle',  ja:'さんかく',      emoji:'🔺', cat:'shapes', grade:5, unit:1 },
  { id:'sh06', en:'diamond',   ja:'ひしがた',      emoji:'💎', cat:'shapes', grade:5, unit:1 },
  { id:'sh07', en:'heart',     ja:'ハート',        emoji:'❤️', cat:'shapes', grade:5, unit:1 },
  { id:'sh08', en:'rectangle', ja:'ちょうほうけい', emoji:'▬', cat:'shapes', grade:5, unit:1 },
  { id:'sh09', en:'oval',      ja:'だえん',        emoji:'🥚', cat:'shapes', grade:5, unit:1 },
  { id:'sh10', en:'crescent',  ja:'みかづき',      emoji:'🌙', cat:'shapes', grade:5, unit:1 },
  { id:'sh11', en:'arrow',     ja:'やじるし',      emoji:'➡️', cat:'shapes', grade:5, unit:1 },
  { id:'sh12', en:'cube',      ja:'りっぽうたい',   emoji:'🧊', cat:'shapes', grade:5, unit:1 },

  // ── SPORTS ────────────────────────────────────────────────────────────────
  { id:'sp01', en:'baseball',       ja:'やきゅう',         emoji:'⚾', cat:'sports', grade:5, unit:3 },
  { id:'sp02', en:'soccer',         ja:'サッカー',         emoji:'⚽', cat:'sports', grade:5, unit:3 },
  { id:'sp03', en:'basketball',     ja:'バスケットボール',  emoji:'🏀', cat:'sports', grade:5, unit:3 },
  { id:'sp04', en:'tennis',         ja:'テニス',           emoji:'🎾', cat:'sports', grade:5, unit:3 },
  { id:'sp05', en:'volleyball',     ja:'バレーボール',     emoji:'🏐', cat:'sports', grade:5, unit:3 },
  { id:'sp06', en:'table tennis',   ja:'たっきゅう',       emoji:'🏓', cat:'sports', grade:5, unit:3 },
  { id:'sp07', en:'badminton',      ja:'バドミントン',     emoji:'🏸', cat:'sports', grade:5, unit:3 },
  { id:'sp08', en:'dodgeball',      ja:'ドッジボール',     emoji:'🔴', cat:'sports', grade:5, unit:3 },
  { id:'sp09', en:'rugby',          ja:'ラグビー',         emoji:'🏉', cat:'sports', grade:5, unit:3 },
  { id:'sp10', en:'cricket',        ja:'クリケット',       emoji:'🏏', cat:'sports', grade:5, unit:3 },
  { id:'sp11', en:'sumo',           ja:'すもう',           emoji:'🤼', cat:'sports', grade:5, unit:3 },
  { id:'sp12', en:'kendo',          ja:'けんど',           emoji:'🥋', cat:'sports', grade:5, unit:3 },
  { id:'sp13', en:'gymnastics',     ja:'たいそう・体操',   emoji:'🤸', cat:'sports', grade:5, unit:3 },
  { id:'sp14', en:'swimming',       ja:'すいえい',         emoji:'🏊', cat:'sports', grade:5, unit:3 },
  { id:'sp15', en:'track and field',ja:'りくじょう',       emoji:'🏃', cat:'sports', grade:5, unit:3 },
  { id:'sp16', en:'skateboarding',  ja:'スケートボード',   emoji:'🛹', cat:'sports', grade:5, unit:3 },
  { id:'sp17', en:'skiing',         ja:'スキー',           emoji:'⛷️', cat:'sports', grade:5, unit:3 },
  { id:'sp18', en:'judo',           ja:'じゅうどう',       emoji:'🥋', cat:'sports', grade:5, unit:3 },
  { id:'sp19', en:'figure skating', ja:'フィギュアスケート',emoji:'⛸️', cat:'sports', grade:5, unit:3 },
  { id:'sp20', en:'fencing',        ja:'フェンシング',     emoji:'🤺', cat:'sports', grade:5, unit:3 },
  { id:'sp21', en:'road cycling',   ja:'ロードサイクリング',emoji:'🚴', cat:'sports', grade:5, unit:3 },
  { id:'sp22', en:'sailing',        ja:'ヨット',           emoji:'⛵', cat:'sports', grade:5, unit:3 },
  { id:'sp23', en:'weightlifting',  ja:'ウエイトリフティング',emoji:'🏋️', cat:'sports', grade:5, unit:3 },
  { id:'sp24', en:'boccia',         ja:'ボッチャ',         emoji:'🎯', cat:'sports', grade:5, unit:3 },
  { id:'sp25', en:'wheelchair tennis',ja:'くるまいすテニス',emoji:'🎾', cat:'sports', grade:5, unit:3 },
  { id:'sp26', en:'ice hockey',     ja:'アイスホッケー',   emoji:'🏒', cat:'sports', grade:5, unit:3 },

  // ── FOOD ──────────────────────────────────────────────────────────────────
  { id:'fd01', en:'rice',         ja:'ごはん',       emoji:'🍚', cat:'food', grade:5, unit:6 },
  { id:'fd02', en:'bread',        ja:'パン',         emoji:'🍞', cat:'food', grade:5, unit:6 },
  { id:'fd03', en:'rice ball',    ja:'おにぎり',     emoji:'🍙', cat:'food', grade:5, unit:6 },
  { id:'fd04', en:'sandwich',     ja:'サンドイッチ',  emoji:'🥪', cat:'food', grade:5, unit:6 },
  { id:'fd05', en:'curry and rice',ja:'カレーライス', emoji:'🍛', cat:'food', grade:5, unit:6 },
  { id:'fd06', en:'pancake',      ja:'パンケーキ',    emoji:'🥞', cat:'food', grade:5, unit:6 },
  { id:'fd07', en:'grilled eel',  ja:'うなぎ',       emoji:'🐍', cat:'food', grade:5, unit:6 },
  { id:'fd08', en:'pizza',        ja:'ピザ',         emoji:'🍕', cat:'food', grade:5, unit:6 },
  { id:'fd09', en:'grilled fish', ja:'さかなのしおやき',emoji:'🐟', cat:'food', grade:5, unit:6 },
  { id:'fd10', en:'hamburger',    ja:'ハンバーガー',  emoji:'🍔', cat:'food', grade:5, unit:6 },
  { id:'fd11', en:'steak',        ja:'ステーキ',     emoji:'🥩', cat:'food', grade:5, unit:6 },
  { id:'fd12', en:'soup',         ja:'スープ',       emoji:'🍲', cat:'food', grade:5, unit:6 },
  { id:'fd13', en:'salad',        ja:'サラダ',       emoji:'🥗', cat:'food', grade:5, unit:6 },
  { id:'fd14', en:'sausage',      ja:'ソーセージ',    emoji:'🌭', cat:'food', grade:5, unit:6 },
  { id:'fd15', en:'pie',          ja:'パイ',         emoji:'🥧', cat:'food', grade:5, unit:6 },
  { id:'fd16', en:'fried chicken',ja:'フライドチキン',emoji:'🍗', cat:'food', grade:5, unit:6 },
  { id:'fd17', en:'omelet',       ja:'オムレツ',     emoji:'🍳', cat:'food', grade:5, unit:6 },
  { id:'fd18', en:'hot dog',      ja:'ホットドッグ',  emoji:'🌭', cat:'food', grade:5, unit:6 },
  { id:'fd19', en:'French fries', ja:'フライドポテト',emoji:'🍟', cat:'food', grade:5, unit:6 },
  { id:'fd20', en:'spaghetti',    ja:'スパゲッティ',  emoji:'🍝', cat:'food', grade:5, unit:6 },
  { id:'fd21', en:'fried noodles',ja:'やきそば',     emoji:'🍜', cat:'food', grade:5, unit:6 },
  { id:'fd22', en:'beef bowl',    ja:'ぎゅうどん',    emoji:'🥣', cat:'food', grade:5, unit:6 },
  { id:'fd23', en:'ramen',        ja:'ラーメン',     emoji:'🍜', cat:'food', grade:5, unit:6 },
  { id:'fd24', en:'sushi',        ja:'すし',         emoji:'🍣', cat:'food', grade:5, unit:6 },
  { id:'fd25', en:'soba',         ja:'そば',         emoji:'🍜', cat:'food', grade:5, unit:6 },
  { id:'fd26', en:'tempura',      ja:'てんぷら',     emoji:'🍤', cat:'food', grade:5, unit:6 },

  // ── DRINKS ────────────────────────────────────────────────────────────────
  { id:'dr01', en:'coffee',        ja:'コーヒー',    emoji:'☕', cat:'drinks', grade:5, unit:6 },
  { id:'dr02', en:'milk',          ja:'ミルク・ぎゅうにゅう',emoji:'🥛', cat:'drinks', grade:5, unit:6 },
  { id:'dr03', en:'tea',           ja:'こうちゃ',    emoji:'🍵', cat:'drinks', grade:5, unit:6 },
  { id:'dr04', en:'water',         ja:'みず',        emoji:'💧', cat:'drinks', grade:5, unit:6 },
  { id:'dr05', en:'green tea',     ja:'おちゃ・りょくちゃ',emoji:'🍵', cat:'drinks', grade:5, unit:6 },
  { id:'dr06', en:'mineral water', ja:'ミネラルウォーター',emoji:'🫙', cat:'drinks', grade:5, unit:6 },
  { id:'dr07', en:'juice',         ja:'ジュース',    emoji:'🍹', cat:'drinks', grade:5, unit:6 },
  { id:'dr08', en:'soda',          ja:'ソーダ',      emoji:'🥤', cat:'drinks', grade:5, unit:6 },
  { id:'dr09', en:'lemonade',      ja:'レモネード',  emoji:'🍋', cat:'drinks', grade:5, unit:6 },
  { id:'dr10', en:'hot cocoa',     ja:'ココア',      emoji:'☕', cat:'drinks', grade:5, unit:6 },
  { id:'dr11', en:'smoothie',      ja:'スムージー',  emoji:'🥤', cat:'drinks', grade:5, unit:6 },
  { id:'dr12', en:'sports drink',  ja:'スポーツドリンク',emoji:'🧃', cat:'drinks', grade:5, unit:6 },

  // ── DESSERTS ──────────────────────────────────────────────────────────────
  { id:'de01', en:'cake',          ja:'ケーキ',      emoji:'🎂', cat:'desserts', grade:5, unit:6 },
  { id:'de02', en:'donut',         ja:'ドーナツ',    emoji:'🍩', cat:'desserts', grade:5, unit:6 },
  { id:'de03', en:'parfait',       ja:'パフェ',      emoji:'🍨', cat:'desserts', grade:5, unit:6 },
  { id:'de04', en:'cream puff',    ja:'シュークリーム',emoji:'🍮', cat:'desserts', grade:5, unit:6 },
  { id:'de05', en:'chocolate',     ja:'チョコレート', emoji:'🍫', cat:'desserts', grade:5, unit:6 },
  { id:'de06', en:'popcorn',       ja:'ポップコーン', emoji:'🍿', cat:'desserts', grade:5, unit:6 },
  { id:'de07', en:'shaved ice',    ja:'かき氷',      emoji:'🍧', cat:'desserts', grade:5, unit:6 },
  { id:'de08', en:'pudding',       ja:'プリン',      emoji:'🍮', cat:'desserts', grade:5, unit:6 },
  { id:'de09', en:'ice cream',     ja:'アイスクリーム',emoji:'🍦', cat:'desserts', grade:5, unit:6 },
  { id:'de10', en:'potato chips',  ja:'ポテトチップス',emoji:'🥔', cat:'desserts', grade:5, unit:6 },

  // ── FRUIT ─────────────────────────────────────────────────────────────────
  { id:'fr01', en:'apple',       ja:'りんご',     emoji:'🍎', cat:'fruit', grade:6, unit:0 },
  { id:'fr02', en:'banana',      ja:'バナナ',     emoji:'🍌', cat:'fruit', grade:6, unit:0 },
  { id:'fr03', en:'cherry',      ja:'さくらんぼ', emoji:'🍒', cat:'fruit', grade:6, unit:0 },
  { id:'fr04', en:'grapes',      ja:'ぶどう',     emoji:'🍇', cat:'fruit', grade:6, unit:0 },
  { id:'fr05', en:'melon',       ja:'メロン',     emoji:'🍈', cat:'fruit', grade:6, unit:0 },
  { id:'fr06', en:'peach',       ja:'もも',       emoji:'🍑', cat:'fruit', grade:6, unit:0 },
  { id:'fr07', en:'pineapple',   ja:'パイナップル',emoji:'🍍', cat:'fruit', grade:6, unit:0 },
  { id:'fr08', en:'watermelon',  ja:'すいか',     emoji:'🍉', cat:'fruit', grade:6, unit:0 },
  { id:'fr09', en:'strawberry',  ja:'いちご',     emoji:'🍓', cat:'fruit', grade:6, unit:0 },
  { id:'fr10', en:'orange',      ja:'オレンジ',   emoji:'🍊', cat:'fruit', grade:6, unit:0 },
  { id:'fr11', en:'kiwi fruit',  ja:'キウイ',     emoji:'🥝', cat:'fruit', grade:6, unit:0 },
  { id:'fr12', en:'lemon',       ja:'レモン',     emoji:'🍋', cat:'fruit', grade:6, unit:0 },

  // ── VEGETABLES ────────────────────────────────────────────────────────────
  { id:'ve01', en:'broccoli',      ja:'ブロッコリー',  emoji:'🥦', cat:'vegetables', grade:6, unit:0 },
  { id:'ve02', en:'cabbage',       ja:'キャベツ',      emoji:'🥬', cat:'vegetables', grade:6, unit:0 },
  { id:'ve03', en:'eggplant',      ja:'なす',          emoji:'🍆', cat:'vegetables', grade:6, unit:0 },
  { id:'ve04', en:'lettuce',       ja:'レタス',        emoji:'🥬', cat:'vegetables', grade:6, unit:0 },
  { id:'ve05', en:'cucumber',      ja:'きゅうり',      emoji:'🥒', cat:'vegetables', grade:6, unit:0 },
  { id:'ve06', en:'corn',          ja:'とうもろこし',   emoji:'🌽', cat:'vegetables', grade:6, unit:0 },
  { id:'ve07', en:'bean',          ja:'まめ',          emoji:'🫘', cat:'vegetables', grade:6, unit:0 },
  { id:'ve08', en:'potato',        ja:'じゃがいも',    emoji:'🥔', cat:'vegetables', grade:6, unit:0 },
  { id:'ve09', en:'spinach',       ja:'ほうれんそう',   emoji:'🌿', cat:'vegetables', grade:6, unit:0 },
  { id:'ve10', en:'onion',         ja:'たまねぎ',      emoji:'🧅', cat:'vegetables', grade:6, unit:0 },
  { id:'ve11', en:'green pepper',  ja:'ピーマン',      emoji:'🫑', cat:'vegetables', grade:6, unit:0 },
  { id:'ve12', en:'mushroom',      ja:'きのこ',        emoji:'🍄', cat:'vegetables', grade:6, unit:0 },
  { id:'ve13', en:'carrot',        ja:'にんじん',      emoji:'🥕', cat:'vegetables', grade:6, unit:0 },
  { id:'ve14', en:'tomato',        ja:'トマト',        emoji:'🍅', cat:'vegetables', grade:6, unit:0 },

  // ── INGREDIENTS ───────────────────────────────────────────────────────────
  { id:'in01', en:'meat',    ja:'にく',         emoji:'🥩', cat:'ingredients', grade:6, unit:0 },
  { id:'in02', en:'fish',    ja:'さかな',       emoji:'🐟', cat:'ingredients', grade:6, unit:0 },
  { id:'in03', en:'ham',     ja:'ハム',         emoji:'🍖', cat:'ingredients', grade:6, unit:0 },
  { id:'in04', en:'cheese',  ja:'チーズ',       emoji:'🧀', cat:'ingredients', grade:6, unit:0 },
  { id:'in05', en:'beef',    ja:'ぎゅうにく',   emoji:'🥩', cat:'ingredients', grade:6, unit:0 },
  { id:'in06', en:'chicken', ja:'とりにく',     emoji:'🍗', cat:'ingredients', grade:6, unit:0 },
  { id:'in07', en:'egg',     ja:'たまご',       emoji:'🥚', cat:'ingredients', grade:6, unit:0 },
  { id:'in08', en:'octopus', ja:'たこ',         emoji:'🐙', cat:'ingredients', grade:6, unit:0 },
  { id:'in09', en:'salmon',  ja:'サーモン',     emoji:'🐟', cat:'ingredients', grade:6, unit:0 },
  { id:'in10', en:'pork',    ja:'ぶたにく',     emoji:'🐷', cat:'ingredients', grade:6, unit:0 },
  { id:'in11', en:'bacon',   ja:'ベーコン',     emoji:'🥓', cat:'ingredients', grade:6, unit:0 },

  // ── TASTES ────────────────────────────────────────────────────────────────
  { id:'ta01', en:'bitter',    ja:'にがい',     emoji:'😖', cat:'tastes', grade:6, unit:0 },
  { id:'ta02', en:'sweet',     ja:'あまい',     emoji:'😋', cat:'tastes', grade:6, unit:0 },
  { id:'ta03', en:'salty',     ja:'しょっぱい', emoji:'😮', cat:'tastes', grade:6, unit:0 },
  { id:'ta04', en:'sour',      ja:'すっぱい',   emoji:'😝', cat:'tastes', grade:6, unit:0 },
  { id:'ta05', en:'spicy',     ja:'からい',     emoji:'🌶️', cat:'tastes', grade:6, unit:0 },
  { id:'ta06', en:'cold',      ja:'つめたい',   emoji:'🥶', cat:'tastes', grade:6, unit:0 },
  { id:'ta07', en:'hot',       ja:'あつい',     emoji:'🥵', cat:'tastes', grade:6, unit:0 },
  { id:'ta08', en:'soft',      ja:'やわらかい', emoji:'☁️', cat:'tastes', grade:6, unit:0 },
  { id:'ta09', en:'hard',      ja:'かたい',     emoji:'🪨', cat:'tastes', grade:6, unit:0 },
  { id:'ta10', en:'delicious', ja:'おいしい',   emoji:'😍', cat:'tastes', grade:6, unit:0 },

  // ── ANIMALS ───────────────────────────────────────────────────────────────
  { id:'an01', en:'bear',       ja:'くま',       emoji:'🐻', cat:'animals', grade:5, unit:3 },
  { id:'an02', en:'elephant',   ja:'ぞう',       emoji:'🐘', cat:'animals', grade:5, unit:3 },
  { id:'an03', en:'tiger',      ja:'とら',       emoji:'🐯', cat:'animals', grade:5, unit:3 },
  { id:'an04', en:'giraffe',    ja:'きりん',     emoji:'🦒', cat:'animals', grade:5, unit:3 },
  { id:'an05', en:'lion',       ja:'ライオン',   emoji:'🦁', cat:'animals', grade:5, unit:3 },
  { id:'an06', en:'horse',      ja:'うま',       emoji:'🐴', cat:'animals', grade:5, unit:3 },
  { id:'an07', en:'monkey',     ja:'さる',       emoji:'🐒', cat:'animals', grade:5, unit:3 },
  { id:'an08', en:'cat',        ja:'ねこ',       emoji:'🐱', cat:'animals', grade:5, unit:3 },
  { id:'an09', en:'dog',        ja:'いぬ',       emoji:'🐶', cat:'animals', grade:5, unit:3 },
  { id:'an10', en:'gorilla',    ja:'ゴリラ',     emoji:'🦍', cat:'animals', grade:5, unit:3 },
  { id:'an11', en:'koala',      ja:'コアラ',     emoji:'🐨', cat:'animals', grade:5, unit:3 },
  { id:'an12', en:'mouse',      ja:'ねずみ',     emoji:'🐭', cat:'animals', grade:5, unit:3 },
  { id:'an13', en:'crocodile',  ja:'わに',       emoji:'🐊', cat:'animals', grade:5, unit:3 },
  { id:'an14', en:'panda',      ja:'パンダ',     emoji:'🐼', cat:'animals', grade:5, unit:3 },
  { id:'an15', en:'camel',      ja:'らくだ',     emoji:'🐪', cat:'animals', grade:5, unit:3 },
  { id:'an16', en:'zebra',      ja:'しまうま',   emoji:'🦓', cat:'animals', grade:5, unit:3 },
  { id:'an17', en:'orangutan',  ja:'オランウータン',emoji:'🦧', cat:'animals', grade:5, unit:3 },
  { id:'an18', en:'fox',        ja:'きつね',     emoji:'🦊', cat:'animals', grade:5, unit:3 },
  { id:'an19', en:'rabbit',     ja:'うさぎ',     emoji:'🐰', cat:'animals', grade:5, unit:3 },
  { id:'an20', en:'bird',       ja:'とり',       emoji:'🐦', cat:'animals', grade:5, unit:3 },
  { id:'an21', en:'frog',       ja:'かえる',     emoji:'🐸', cat:'animals', grade:5, unit:3 },
  { id:'an22', en:'snake',      ja:'へび',       emoji:'🐍', cat:'animals', grade:5, unit:3 },

  // ── SEA ANIMALS ───────────────────────────────────────────────────────────
  { id:'sa01', en:'whale',     ja:'くじら',   emoji:'🐳', cat:'sea-animals', grade:6, unit:5 },
  { id:'sa02', en:'dolphin',   ja:'イルカ',   emoji:'🐬', cat:'sea-animals', grade:6, unit:5 },
  { id:'sa03', en:'shark',     ja:'さめ',     emoji:'🦈', cat:'sea-animals', grade:6, unit:5 },
  { id:'sa04', en:'crab',      ja:'かに',     emoji:'🦀', cat:'sea-animals', grade:6, unit:5 },
  { id:'sa05', en:'jellyfish', ja:'くらげ',   emoji:'🪼', cat:'sea-animals', grade:6, unit:5 },
  { id:'sa06', en:'penguin',   ja:'ペンギン', emoji:'🐧', cat:'sea-animals', grade:6, unit:5 },
  { id:'sa07', en:'sea turtle',ja:'うみがめ', emoji:'🐢', cat:'sea-animals', grade:6, unit:5 },
  { id:'sa08', en:'fish',      ja:'さかな',   emoji:'🐠', cat:'sea-animals', grade:6, unit:5 },
  { id:'sa09', en:'octopus',   ja:'たこ',     emoji:'🐙', cat:'sea-animals', grade:6, unit:5 },
  { id:'sa10', en:'seal',      ja:'あざらし', emoji:'🦭', cat:'sea-animals', grade:6, unit:5 },
  { id:'sa11', en:'sea otter', ja:'らっこ',   emoji:'🦦', cat:'sea-animals', grade:6, unit:5 },
  { id:'sa12', en:'starfish',  ja:'ヒトデ',   emoji:'⭐', cat:'sea-animals', grade:6, unit:5 },

  // ── BUGS ──────────────────────────────────────────────────────────────────
  { id:'bu01', en:'ant',          ja:'あり',       emoji:'🐜', cat:'bugs', grade:6, unit:5 },
  { id:'bu02', en:'beetle',       ja:'かぶとむし', emoji:'🪲', cat:'bugs', grade:6, unit:5 },
  { id:'bu03', en:'stag beetle',  ja:'くわがたむし',emoji:'🪲', cat:'bugs', grade:6, unit:5 },
  { id:'bu04', en:'spider',       ja:'くも',       emoji:'🕷️', cat:'bugs', grade:6, unit:5 },
  { id:'bu05', en:'grasshopper',  ja:'バッタ',     emoji:'🦗', cat:'bugs', grade:6, unit:5 },
  { id:'bu06', en:'mantis',       ja:'カマキリ',   emoji:'🦗', cat:'bugs', grade:6, unit:5 },
  { id:'bu07', en:'butterfly',    ja:'ちょうちょ', emoji:'🦋', cat:'bugs', grade:6, unit:5 },
  { id:'bu08', en:'dragonfly',    ja:'とんぼ',     emoji:'🪰', cat:'bugs', grade:6, unit:5 },
  { id:'bu09', en:'ladybug',      ja:'てんとうむし',emoji:'🐞', cat:'bugs', grade:6, unit:5 },
  { id:'bu10', en:'bee',          ja:'はち',       emoji:'🐝', cat:'bugs', grade:6, unit:5 },
  { id:'bu11', en:'caterpillar',  ja:'いもむし',   emoji:'🐛', cat:'bugs', grade:6, unit:5 },
  { id:'bu12', en:'snail',        ja:'かたつむり', emoji:'🐌', cat:'bugs', grade:6, unit:5 },

  // ── NATURE ────────────────────────────────────────────────────────────────
  { id:'na01', en:'mountain',   ja:'やま',     emoji:'🏔️', cat:'nature', grade:5, unit:0 },
  { id:'na02', en:'lake',       ja:'みずうみ', emoji:'🏞️', cat:'nature', grade:5, unit:0 },
  { id:'na03', en:'rainforest', ja:'熱帯雨林', emoji:'🌴', cat:'nature', grade:5, unit:0 },
  { id:'na04', en:'sea',        ja:'うみ',     emoji:'🌊', cat:'nature', grade:5, unit:0 },
  { id:'na05', en:'savanna',    ja:'サバンナ', emoji:'🌾', cat:'nature', grade:5, unit:0 },
  { id:'na06', en:'forest',     ja:'もり',     emoji:'🌲', cat:'nature', grade:5, unit:0 },
  { id:'na07', en:'river',      ja:'かわ',     emoji:'🏞️', cat:'nature', grade:5, unit:0 },
  { id:'na08', en:'desert',     ja:'さばく',   emoji:'🏜️', cat:'nature', grade:5, unit:0 },
  { id:'na09', en:'island',    ja:'しま',     emoji:'🏝️', cat:'nature', grade:5, unit:0 },
  { id:'na10', en:'waterfall', ja:'たき',     emoji:'💦', cat:'nature', grade:5, unit:0 },
  { id:'na11', en:'hill',      ja:'おか',     emoji:'⛰️', cat:'nature', grade:5, unit:0 },
  { id:'na12', en:'valley',    ja:'たに',     emoji:'🏞️', cat:'nature', grade:5, unit:0 },

  // ── TIME (months, days, seasons) ─────────────────────────────────────────
  { id:'mo01', en:'January',   ja:'いちがつ・1月', emoji:'❄️', cat:'time', grade:5, unit:2 },
  { id:'mo02', en:'February',  ja:'にがつ・2月',   emoji:'💝', cat:'time', grade:5, unit:2 },
  { id:'mo03', en:'March',     ja:'さんがつ・3月', emoji:'🌸', cat:'time', grade:5, unit:2 },
  { id:'mo04', en:'April',     ja:'しがつ・4月',   emoji:'🌷', cat:'time', grade:5, unit:2 },
  { id:'mo05', en:'May',       ja:'ごがつ・5月',   emoji:'🌿', cat:'time', grade:5, unit:2 },
  { id:'mo06', en:'June',      ja:'ろくがつ・6月', emoji:'☔', cat:'time', grade:5, unit:2 },
  { id:'mo07', en:'July',      ja:'しちがつ・7月', emoji:'🌻', cat:'time', grade:5, unit:2 },
  { id:'mo08', en:'August',    ja:'はちがつ・8月', emoji:'🏖️', cat:'time', grade:5, unit:2 },
  { id:'mo09', en:'September', ja:'くがつ・9月',   emoji:'🍂', cat:'time', grade:5, unit:2 },
  { id:'mo10', en:'October',   ja:'じゅうがつ・10月',emoji:'🎃', cat:'time', grade:5, unit:2 },
  { id:'mo11', en:'November',  ja:'じゅういちがつ・11月',emoji:'🍁', cat:'time', grade:5, unit:2 },
  { id:'mo12', en:'December',  ja:'じゅうにがつ・12月',emoji:'🎄', cat:'time', grade:5, unit:2 },
  { id:'dy01', en:'Sunday',    ja:'にちようび',    emoji:'☀️', cat:'time', grade:5, unit:2 },
  { id:'dy02', en:'Monday',    ja:'げつようび',    emoji:'📅', cat:'time', grade:5, unit:2 },
  { id:'dy03', en:'Tuesday',   ja:'かようび',      emoji:'📅', cat:'time', grade:5, unit:2 },
  { id:'dy04', en:'Wednesday', ja:'すいようび',    emoji:'📅', cat:'time', grade:5, unit:2 },
  { id:'dy05', en:'Thursday',  ja:'もくようび',    emoji:'📅', cat:'time', grade:5, unit:2 },
  { id:'dy06', en:'Friday',    ja:'きんようび',    emoji:'🎉', cat:'time', grade:5, unit:2 },
  { id:'dy07', en:'Saturday',  ja:'どようび',      emoji:'🎮', cat:'time', grade:5, unit:2 },
  { id:'se01', en:'spring',    ja:'はる',          emoji:'🌸', cat:'time', grade:5, unit:2 },
  { id:'se02', en:'summer',    ja:'なつ',          emoji:'☀️', cat:'time', grade:5, unit:2 },
  { id:'se03', en:'fall',      ja:'あき',          emoji:'🍂', cat:'time', grade:5, unit:2 },
  { id:'se04', en:'winter',    ja:'ふゆ',          emoji:'❄️', cat:'time', grade:5, unit:2 },

  // ── WEATHER ───────────────────────────────────────────────────────────────
  { id:'we01', en:'sunny',   ja:'はれ',    emoji:'☀️', cat:'weather', grade:5, unit:0 },
  { id:'we02', en:'cloudy',  ja:'くもり',  emoji:'☁️', cat:'weather', grade:5, unit:0 },
  { id:'we03', en:'windy',   ja:'かぜが強い',emoji:'💨', cat:'weather', grade:5, unit:0 },
  { id:'we04', en:'rainy',   ja:'あめ',    emoji:'🌧️', cat:'weather', grade:5, unit:0 },
  { id:'we05', en:'snowy',   ja:'ゆき',    emoji:'❄️', cat:'weather', grade:5, unit:0 },
  { id:'we06', en:'cold',    ja:'さむい',  emoji:'🥶', cat:'weather', grade:5, unit:0 },
  { id:'we07', en:'warm',    ja:'あたたかい',emoji:'🌤️', cat:'weather', grade:5, unit:0 },
  { id:'we08', en:'hot',     ja:'あつい',  emoji:'🌡️', cat:'weather', grade:5, unit:0 },
  { id:'we09', en:'humid',   ja:'むしあつい',emoji:'😓', cat:'weather', grade:5, unit:0 },
  { id:'we10', en:'foggy',   ja:'きり',      emoji:'🌫️', cat:'weather', grade:5, unit:0 },
  { id:'we11', en:'cool',    ja:'すずしい',  emoji:'🍃', cat:'weather', grade:5, unit:0 },
  { id:'we12', en:'stormy',  ja:'あらし',    emoji:'⛈️', cat:'weather', grade:5, unit:0 },

  // ── PEOPLE ────────────────────────────────────────────────────────────────
  { id:'pe01', en:'man',        ja:'おとこのひと', emoji:'👨', cat:'people', grade:5, unit:4 },
  { id:'pe02', en:'woman',      ja:'おんなのひと', emoji:'👩', cat:'people', grade:5, unit:4 },
  { id:'pe03', en:'boy',        ja:'おとこのこ',   emoji:'👦', cat:'people', grade:5, unit:4 },
  { id:'pe04', en:'girl',       ja:'おんなのこ',   emoji:'👧', cat:'people', grade:5, unit:4 },
  { id:'pe05', en:'child',      ja:'こども',       emoji:'🧒', cat:'people', grade:5, unit:4 },
  { id:'pe06', en:'baby',       ja:'あかちゃん',   emoji:'👶', cat:'people', grade:5, unit:4 },
  { id:'pe07', en:'friends',    ja:'ともだち',     emoji:'👫', cat:'people', grade:5, unit:4 },
  { id:'pe08', en:'classmates', ja:'クラスメート', emoji:'🏫', cat:'people', grade:5, unit:4 },
  { id:'pe09', en:'adult',      ja:'おとな',       emoji:'🧑', cat:'people', grade:5, unit:4 },
  { id:'pe10', en:'everyone',   ja:'みんな',       emoji:'👥', cat:'people', grade:5, unit:4 },
  { id:'pe11', en:'teammate',   ja:'チームメイト', emoji:'🤝', cat:'people', grade:5, unit:4 },
  { id:'pe12', en:'neighbor',   ja:'きんじょのひと',emoji:'🏘️', cat:'people', grade:5, unit:4 },

  // ── FAMILY ────────────────────────────────────────────────────────────────
  { id:'fa01', en:'grandfather', ja:'おじいさん', emoji:'👴', cat:'family', grade:5, unit:4 },
  { id:'fa02', en:'grandmother', ja:'おばあさん', emoji:'👵', cat:'family', grade:5, unit:4 },
  { id:'fa03', en:'father',      ja:'おとうさん', emoji:'👨', cat:'family', grade:5, unit:4 },
  { id:'fa04', en:'mother',      ja:'おかあさん', emoji:'👩', cat:'family', grade:5, unit:4 },
  { id:'fa05', en:'parents',     ja:'りょうしん', emoji:'👪', cat:'family', grade:5, unit:4 },
  { id:'fa06', en:'brother',     ja:'おにいさん・おとうと',emoji:'👦', cat:'family', grade:5, unit:4 },
  { id:'fa07', en:'sister',      ja:'おねえさん・いもうと',emoji:'👧', cat:'family', grade:5, unit:4 },
  { id:'fa08', en:'uncle',       ja:'おじさん',   emoji:'👨', cat:'family', grade:5, unit:4 },
  { id:'fa09', en:'aunt',        ja:'おばさん',   emoji:'👩', cat:'family', grade:5, unit:4 },
  { id:'fa10', en:'cousin',      ja:'いとこ',     emoji:'🧒', cat:'family', grade:5, unit:4 },

  // ── PERSONALITIES ─────────────────────────────────────────────────────────
  { id:'pr01', en:'shy',      ja:'はずかしがりや',emoji:'🙈', cat:'personalities', grade:5, unit:4 },
  { id:'pr02', en:'active',   ja:'かつどうてき',  emoji:'🏃', cat:'personalities', grade:5, unit:4 },
  { id:'pr03', en:'brave',    ja:'ゆうかん',      emoji:'💪', cat:'personalities', grade:5, unit:4 },
  { id:'pr04', en:'smart',    ja:'かしこい',      emoji:'🧠', cat:'personalities', grade:5, unit:4 },
  { id:'pr05', en:'friendly', ja:'しんせつ',      emoji:'😊', cat:'personalities', grade:5, unit:4 },
  { id:'pr06', en:'funny',    ja:'おもしろい',    emoji:'😂', cat:'personalities', grade:5, unit:4 },
  { id:'pr07', en:'kind',     ja:'やさしい',      emoji:'🥰', cat:'personalities', grade:5, unit:4 },
  { id:'pr08', en:'strong',   ja:'つよい',        emoji:'💪', cat:'personalities', grade:5, unit:4 },
  { id:'pr09', en:'cheerful', ja:'あかるい',      emoji:'😄', cat:'personalities', grade:5, unit:4 },
  { id:'pr10', en:'honest',   ja:'しょうじき',    emoji:'🙂', cat:'personalities', grade:5, unit:4 },
  { id:'pr11', en:'quiet',    ja:'しずか',        emoji:'🤫', cat:'personalities', grade:5, unit:4 },
  { id:'pr12', en:'polite',   ja:'れいぎ正しい',  emoji:'🙇', cat:'personalities', grade:5, unit:4 },

  // ── ACTIONS (5th grade) ───────────────────────────────────────────────────
  { id:'ac01', en:'spell',   ja:'つづりを言う',   emoji:'🔤', cat:'actions', grade:5, unit:1 },
  { id:'ac02', en:'walk',    ja:'あるく',         emoji:'🚶', cat:'actions', grade:5, unit:3 },
  { id:'ac03', en:'run',     ja:'はしる',         emoji:'🏃', cat:'actions', grade:5, unit:3 },
  { id:'ac04', en:'fly',     ja:'とぶ',           emoji:'✈️', cat:'actions', grade:5, unit:3 },
  { id:'ac05', en:'like',    ja:'すきだ',         emoji:'❤️', cat:'actions', grade:5, unit:1 },
  { id:'ac06', en:'listen',  ja:'きく',           emoji:'👂', cat:'actions', grade:5, unit:3 },
  { id:'ac07', en:'dance',   ja:'おどる',         emoji:'💃', cat:'actions', grade:5, unit:3 },
  { id:'ac08', en:'sing',    ja:'うたう',         emoji:'🎤', cat:'actions', grade:5, unit:3 },
  { id:'ac09', en:'jump',    ja:'とぶ・ジャンプ', emoji:'🦘', cat:'actions', grade:5, unit:3 },
  { id:'ac10', en:'want',    ja:'ほしい',         emoji:'🙏', cat:'actions', grade:5, unit:2 },
  { id:'ac11', en:'look',    ja:'みる',           emoji:'👀', cat:'actions', grade:5, unit:3 },
  { id:'ac12', en:'cook',    ja:'りょうりする',   emoji:'👨‍🍳', cat:'actions', grade:5, unit:4 },
  { id:'ac13', en:'see',     ja:'みえる',         emoji:'👁️', cat:'actions', grade:5, unit:3 },
  { id:'ac14', en:'go',      ja:'いく',           emoji:'🚶', cat:'actions', grade:5, unit:5 },
  { id:'ac15', en:'swim',    ja:'およぐ',         emoji:'🏊', cat:'actions', grade:5, unit:3 },
  { id:'ac16', en:'eat',     ja:'たべる',         emoji:'🍽️', cat:'actions', grade:5, unit:6 },
  { id:'ac17', en:'buy',     ja:'かう',           emoji:'🛍️', cat:'actions', grade:5, unit:6 },
  { id:'ac18', en:'turn',    ja:'まがる',         emoji:'↩️', cat:'actions', grade:5, unit:5 },
  { id:'ac19', en:'catch',   ja:'つかまえる',     emoji:'🤲', cat:'actions', grade:5, unit:3 },
  { id:'ac20', en:'play',    ja:'あそぶ・する',   emoji:'⚽', cat:'actions', grade:5, unit:3 },
  { id:'ac21', en:'drink',   ja:'のむ',           emoji:'🥤', cat:'actions', grade:5, unit:6 },
  { id:'ac22', en:'have',    ja:'もっている',     emoji:'🤲', cat:'actions', grade:5, unit:6 },
  { id:'ac23', en:'speak',   ja:'はなす',         emoji:'💬', cat:'actions', grade:6, unit:1 },
  { id:'ac24', en:'watch',   ja:'みる',           emoji:'📺', cat:'actions', grade:6, unit:1 },
  { id:'ac25', en:'read',    ja:'よむ',           emoji:'📖', cat:'actions', grade:6, unit:1 },
  { id:'ac26', en:'live',    ja:'すむ・いきている',emoji:'🏠', cat:'actions', grade:6, unit:1 },
  { id:'ac27', en:'make',    ja:'つくる',         emoji:'🔨', cat:'actions', grade:6, unit:1 },
  { id:'ac28', en:'help',    ja:'たすける',       emoji:'🤝', cat:'actions', grade:6, unit:5 },
  { id:'ac29', en:'ride',    ja:'のる',           emoji:'🚴', cat:'actions', grade:6, unit:1 },
  { id:'ac30', en:'study',   ja:'べんきょうする', emoji:'📚', cat:'actions', grade:6, unit:1 },
  { id:'ac31', en:'come',    ja:'くる',           emoji:'👋', cat:'actions', grade:6, unit:1 },
  { id:'ac32', en:'wear',    ja:'きている',       emoji:'👕', cat:'actions', grade:6, unit:1 },
  { id:'ac33', en:'practice',ja:'れんしゅうする', emoji:'🎯', cat:'actions', grade:6, unit:1 },
  { id:'ac34', en:'join',    ja:'さんかする',     emoji:'🤝', cat:'actions', grade:6, unit:8 },
  { id:'ac35', en:'get',     ja:'もらう・手に入れる',emoji:'🎁', cat:'actions', grade:6, unit:1 },
  { id:'ac36', en:'clean',   ja:'そうじする',     emoji:'🧹', cat:'actions', grade:6, unit:1 },
  { id:'ac37', en:'talk',    ja:'はなす',         emoji:'💬', cat:'actions', grade:6, unit:1 },
  { id:'ac38', en:'work',    ja:'はたらく',       emoji:'💼', cat:'actions', grade:6, unit:8 },
  { id:'ac39', en:'enjoy',   ja:'たのしむ',       emoji:'😊', cat:'actions', grade:6, unit:1 },
  { id:'ac40', en:'visit',   ja:'たずねる',       emoji:'🏃', cat:'actions', grade:6, unit:7 },
  { id:'ac41', en:'stop',    ja:'とまる・やめる', emoji:'✋', cat:'actions', grade:6, unit:5 },
  { id:'ac42', en:'save',    ja:'たすける・のこす',emoji:'💾', cat:'actions', grade:6, unit:6 },
  { id:'ac43', en:'went',    ja:'いった',         emoji:'🚶', cat:'actions', grade:6, unit:2 },
  { id:'ac44', en:'ate',     ja:'たべた',         emoji:'🍽️', cat:'actions', grade:6, unit:2 },
  { id:'ac45', en:'saw',     ja:'みた',           emoji:'👁️', cat:'actions', grade:6, unit:2 },
  { id:'ac46', en:'had',     ja:'もっていた',     emoji:'🤲', cat:'actions', grade:6, unit:2 },
  { id:'ac47', en:'made',    ja:'つくった',       emoji:'🔨', cat:'actions', grade:6, unit:2 },
  { id:'ac48', en:'played',  ja:'あそんだ・した', emoji:'⚽', cat:'actions', grade:6, unit:2 },
  { id:'ac49', en:'watched', ja:'みた',           emoji:'📺', cat:'actions', grade:6, unit:2 },
  { id:'ac50', en:'enjoyed', ja:'たのしんだ',     emoji:'😊', cat:'actions', grade:6, unit:2 },

  // ── DAILY ACTIVITIES ──────────────────────────────────────────────────────
  { id:'da01', en:'always',              ja:'いつも',         emoji:'🔄', cat:'daily', grade:6, unit:1 },
  { id:'da02', en:'usually',             ja:'たいてい',       emoji:'📊', cat:'daily', grade:6, unit:1 },
  { id:'da03', en:'sometimes',           ja:'ときどき',       emoji:'📊', cat:'daily', grade:6, unit:1 },
  { id:'da04', en:'never',               ja:'けっして〜ない', emoji:'🚫', cat:'daily', grade:6, unit:1 },
  { id:'da05', en:'get up',              ja:'おきる',         emoji:'⏰', cat:'daily', grade:6, unit:1 },
  { id:'da06', en:'have breakfast',      ja:'あさごはんをたべる',emoji:'🍳', cat:'daily', grade:6, unit:1 },
  { id:'da07', en:'go to school',        ja:'がっこうへいく', emoji:'🏫', cat:'daily', grade:6, unit:1 },
  { id:'da08', en:'have lunch',          ja:'ひるごはんをたべる',emoji:'🥗', cat:'daily', grade:6, unit:1 },
  { id:'da09', en:'go home',             ja:'いえへかえる',   emoji:'🏠', cat:'daily', grade:6, unit:1 },
  { id:'da10', en:'have dinner',         ja:'ばんごはんをたべる',emoji:'🍽️', cat:'daily', grade:6, unit:1 },
  { id:'da11', en:'watch TV',            ja:'テレビをみる',   emoji:'📺', cat:'daily', grade:6, unit:1 },
  { id:'da12', en:'do my homework',      ja:'しゅくだいをする',emoji:'📚', cat:'daily', grade:6, unit:1 },
  { id:'da13', en:'take a bath',         ja:'おふろにはいる', emoji:'🛁', cat:'daily', grade:6, unit:1 },
  { id:'da14', en:'go to bed',           ja:'ねる',           emoji:'🛏️', cat:'daily', grade:6, unit:1 },
  { id:'da15', en:'brush my teeth',      ja:'はをみがく',     emoji:'🪥', cat:'daily', grade:6, unit:1 },
  { id:'da16', en:'walk my dog',         ja:'いぬのさんぽをする',emoji:'🐕', cat:'daily', grade:6, unit:1 },
  { id:'da17', en:'wash the dishes',     ja:'さらをあらう',   emoji:'🍽️', cat:'daily', grade:6, unit:1 },
  { id:'da18', en:'clean my room',       ja:'へやをそうじする',emoji:'🧹', cat:'daily', grade:6, unit:1 },
  { id:'da19', en:'study English',       ja:'えいごをべんきょうする',emoji:'📖', cat:'daily', grade:6, unit:1 },
  { id:'da20', en:'play soccer',         ja:'サッカーをする', emoji:'⚽', cat:'daily', grade:6, unit:1 },

  // ── CLOTHES ───────────────────────────────────────────────────────────────
  { id:'cl01', en:'shirt',      ja:'シャツ',         emoji:'👔', cat:'clothes', grade:6, unit:0 },
  { id:'cl02', en:'pants',      ja:'ズボン・パンツ', emoji:'👖', cat:'clothes', grade:6, unit:0 },
  { id:'cl03', en:'shoes',      ja:'くつ',           emoji:'👟', cat:'clothes', grade:6, unit:0 },
  { id:'cl04', en:'socks',      ja:'くつした',       emoji:'🧦', cat:'clothes', grade:6, unit:0 },
  { id:'cl05', en:'T-shirt',    ja:'Tシャツ',        emoji:'👕', cat:'clothes', grade:6, unit:0 },
  { id:'cl06', en:'jeans',      ja:'ジーンズ',       emoji:'👖', cat:'clothes', grade:6, unit:0 },
  { id:'cl07', en:'sweatshirt', ja:'スウェットシャツ',emoji:'🧥', cat:'clothes', grade:6, unit:0 },
  { id:'cl08', en:'cap',        ja:'ぼうし',         emoji:'🧢', cat:'clothes', grade:6, unit:0 },
  { id:'cl09', en:'hat',        ja:'ハット',         emoji:'🎩', cat:'clothes', grade:6, unit:0 },
  { id:'cl10', en:'sweater',    ja:'セーター',       emoji:'🧶', cat:'clothes', grade:6, unit:0 },
  { id:'cl11', en:'uniform',    ja:'せいふく',       emoji:'👔', cat:'clothes', grade:6, unit:0 },
  { id:'cl12', en:'gloves',     ja:'てぶくろ',       emoji:'🧤', cat:'clothes', grade:6, unit:0 },

  // ── BODY ──────────────────────────────────────────────────────────────────
  { id:'bo01', en:'head',      ja:'あたま',     emoji:'🗣️', cat:'body', grade:5, unit:0 },
  { id:'bo02', en:'hair',      ja:'かみ',       emoji:'💇', cat:'body', grade:5, unit:0 },
  { id:'bo03', en:'face',      ja:'かお',       emoji:'😊', cat:'body', grade:5, unit:0 },
  { id:'bo04', en:'eye',       ja:'め',         emoji:'👁️', cat:'body', grade:5, unit:0 },
  { id:'bo05', en:'ear',       ja:'みみ',       emoji:'👂', cat:'body', grade:5, unit:0 },
  { id:'bo06', en:'nose',      ja:'はな',       emoji:'👃', cat:'body', grade:5, unit:0 },
  { id:'bo07', en:'mouth',     ja:'くち',       emoji:'👄', cat:'body', grade:5, unit:0 },
  { id:'bo08', en:'teeth',     ja:'は',         emoji:'🦷', cat:'body', grade:5, unit:0 },
  { id:'bo09', en:'neck',      ja:'くび',       emoji:'🙆', cat:'body', grade:5, unit:0 },
  { id:'bo10', en:'shoulder',  ja:'かた',       emoji:'💪', cat:'body', grade:5, unit:0 },
  { id:'bo11', en:'arm',       ja:'うで',       emoji:'💪', cat:'body', grade:5, unit:0 },
  { id:'bo12', en:'hand',      ja:'て',         emoji:'✋', cat:'body', grade:5, unit:0 },
  { id:'bo13', en:'fingers',   ja:'ゆび',       emoji:'☝️', cat:'body', grade:5, unit:0 },
  { id:'bo14', en:'stomach',   ja:'おなか',     emoji:'🫃', cat:'body', grade:5, unit:0 },
  { id:'bo15', en:'leg',       ja:'あし',       emoji:'🦵', cat:'body', grade:5, unit:0 },
  { id:'bo16', en:'knee',      ja:'ひざ',       emoji:'🦵', cat:'body', grade:5, unit:0 },
  { id:'bo17', en:'foot',      ja:'あし・足',   emoji:'🦶', cat:'body', grade:5, unit:0 },
  { id:'bo18', en:'toe',       ja:'あしのゆび', emoji:'🦶', cat:'body', grade:5, unit:0 },

  // ── TOWN ──────────────────────────────────────────────────────────────────
  { id:'to01', en:'house',            ja:'いえ',         emoji:'🏠', cat:'town', grade:5, unit:5 },
  { id:'to02', en:'bus stop',         ja:'バスてい',     emoji:'🚌', cat:'town', grade:5, unit:5 },
  { id:'to03', en:'bookstore',        ja:'ほんや',       emoji:'📚', cat:'town', grade:5, unit:5 },
  { id:'to04', en:'park',             ja:'こうえん',     emoji:'🌳', cat:'town', grade:5, unit:5 },
  { id:'to05', en:'library',          ja:'としょかん',   emoji:'📖', cat:'town', grade:5, unit:5 },
  { id:'to06', en:'station',          ja:'えき',         emoji:'🚉', cat:'town', grade:5, unit:5 },
  { id:'to07', en:'restaurant',       ja:'レストラン',   emoji:'🍽️', cat:'town', grade:5, unit:5 },
  { id:'to08', en:'church',           ja:'きょうかい',   emoji:'⛪', cat:'town', grade:5, unit:5 },
  { id:'to09', en:'museum',           ja:'はくぶつかん', emoji:'🏛️', cat:'town', grade:5, unit:5 },
  { id:'to10', en:'hospital',         ja:'びょういん',   emoji:'🏥', cat:'town', grade:5, unit:5 },
  { id:'to11', en:'post office',      ja:'ゆうびんきょく',emoji:'📮', cat:'town', grade:5, unit:5 },
  { id:'to12', en:'shrine',           ja:'じんじゃ',     emoji:'⛩️', cat:'town', grade:5, unit:5 },
  { id:'to13', en:'zoo',              ja:'どうぶつえん', emoji:'🦁', cat:'town', grade:5, unit:5 },
  { id:'to14', en:'fire station',     ja:'しょうぼうしょ',emoji:'🚒', cat:'town', grade:5, unit:5 },
  { id:'to15', en:'castle',           ja:'しろ',         emoji:'🏯', cat:'town', grade:5, unit:5 },
  { id:'to16', en:'stadium',          ja:'スタジアム',   emoji:'🏟️', cat:'town', grade:5, unit:5 },
  { id:'to17', en:'aquarium',         ja:'すいぞくかん', emoji:'🐠', cat:'town', grade:5, unit:5 },
  { id:'to18', en:'police station',   ja:'けいさつしょ', emoji:'🚔', cat:'town', grade:5, unit:5 },
  { id:'to19', en:'supermarket',      ja:'スーパーマーケット',emoji:'🛒', cat:'town', grade:5, unit:5 },
  { id:'to20', en:'convenience store',ja:'コンビニ',     emoji:'🏪', cat:'town', grade:5, unit:5 },
  { id:'to21', en:'amusement park',   ja:'ゆうえんち',   emoji:'🎡', cat:'town', grade:5, unit:5 },
  { id:'to22', en:'elementary school',ja:'しょうがっこう',emoji:'🏫', cat:'town', grade:5, unit:5 },
  { id:'to23', en:'junior high school',ja:'ちゅうがっこう',emoji:'🏫', cat:'town', grade:5, unit:5 },
  { id:'to24', en:'temple',           ja:'てら',         emoji:'🛕', cat:'town', grade:5, unit:5 },
  { id:'to25', en:'bike',             ja:'じてんしゃ',   emoji:'🚲', cat:'town', grade:5, unit:5 },
  { id:'to26', en:'bus',              ja:'バス',         emoji:'🚌', cat:'town', grade:5, unit:5 },
  { id:'to27', en:'train',            ja:'でんしゃ',     emoji:'🚃', cat:'town', grade:5, unit:5 },
  { id:'to28', en:'taxi',             ja:'タクシー',     emoji:'🚕', cat:'town', grade:5, unit:5 },

  // ── SCHOOL (subjects + rooms) ─────────────────────────────────────────────
  { id:'sc01', en:'English',                     ja:'えいご',   emoji:'🔤', cat:'school', grade:5, unit:1 },
  { id:'sc02', en:'Japanese',                    ja:'こくご',   emoji:'📜', cat:'school', grade:5, unit:1 },
  { id:'sc03', en:'math',                        ja:'さんすう', emoji:'➕', cat:'school', grade:5, unit:1 },
  { id:'sc04', en:'music',                       ja:'おんがく', emoji:'🎵', cat:'school', grade:5, unit:1 },
  { id:'sc05', en:'science',                     ja:'りか',     emoji:'🔬', cat:'school', grade:5, unit:1 },
  { id:'sc06', en:'social studies',              ja:'しゃかい', emoji:'🌍', cat:'school', grade:5, unit:1 },
  { id:'sc07', en:'arts and crafts',             ja:'ずこう',   emoji:'🎨', cat:'school', grade:5, unit:1 },
  { id:'sc08', en:'calligraphy',                 ja:'しょどう', emoji:'✒️', cat:'school', grade:5, unit:1 },
  { id:'sc09', en:'home economics',              ja:'かていか', emoji:'🍳', cat:'school', grade:5, unit:1 },
  { id:'sc10', en:'moral education',             ja:'どうとく', emoji:'💭', cat:'school', grade:5, unit:1 },
  { id:'sc11', en:'PE',                          ja:'たいいく', emoji:'⚽', cat:'school', grade:5, unit:1 },
  { id:'sc12', en:'classroom',                   ja:'きょうしつ',emoji:'🏫', cat:'school', grade:5, unit:0 },
  { id:'sc13', en:'library',                     ja:'としょしつ',emoji:'📚', cat:'school', grade:5, unit:0 },
  { id:'sc14', en:'gym',                         ja:'たいいくかん',emoji:'🏋️', cat:'school', grade:5, unit:0 },
  { id:'sc15', en:'music room',                  ja:'おんがくしつ',emoji:'🎵', cat:'school', grade:5, unit:0 },
  { id:'sc16', en:'computer room',               ja:'コンピューターしつ',emoji:'💻', cat:'school', grade:5, unit:0 },
  { id:'sc17', en:'playground',                  ja:'うんどうじょう',emoji:'🏃', cat:'school', grade:5, unit:0 },
  { id:'sc18', en:'swimming pool',               ja:'プール',   emoji:'🏊', cat:'school', grade:5, unit:0 },
  { id:'sc19', en:'teachers\' office',           ja:'しょくいんしつ',emoji:'📋', cat:'school', grade:5, unit:0 },

  // ── STATIONERY ────────────────────────────────────────────────────────────
  { id:'st01', en:'crayon',          ja:'クレヨン',     emoji:'🖍️', cat:'stationery', grade:5, unit:2 },
  { id:'st02', en:'marker',          ja:'マーカー',     emoji:'🖊️', cat:'stationery', grade:5, unit:2 },
  { id:'st03', en:'eraser',          ja:'けしゴム',     emoji:'🧹', cat:'stationery', grade:5, unit:2 },
  { id:'st04', en:'ruler',           ja:'じょうぎ',     emoji:'📏', cat:'stationery', grade:5, unit:2 },
  { id:'st05', en:'pen',             ja:'ペン',         emoji:'🖊️', cat:'stationery', grade:5, unit:2 },
  { id:'st06', en:'pencil',          ja:'えんぴつ',     emoji:'✏️', cat:'stationery', grade:5, unit:2 },
  { id:'st07', en:'pencil case',     ja:'ふでばこ',     emoji:'📦', cat:'stationery', grade:5, unit:2 },
  { id:'st08', en:'scissors',        ja:'はさみ',       emoji:'✂️', cat:'stationery', grade:5, unit:2 },
  { id:'st09', en:'glue',            ja:'のり',         emoji:'🫧', cat:'stationery', grade:5, unit:2 },
  { id:'st10', en:'stapler',         ja:'ホッチキス',   emoji:'📌', cat:'stationery', grade:5, unit:2 },
  { id:'st11', en:'notebook',        ja:'ノート',       emoji:'📓', cat:'stationery', grade:5, unit:2 },
  { id:'st12', en:'pencil sharpener',ja:'えんぴつけずり',emoji:'✏️', cat:'stationery', grade:5, unit:2 },

  // ── MUSICAL INSTRUMENTS ───────────────────────────────────────────────────
  { id:'mi01', en:'recorder',           ja:'リコーダー',       emoji:'🎵', cat:'instruments', grade:5, unit:3 },
  { id:'mi02', en:'violin',             ja:'バイオリン',       emoji:'🎻', cat:'instruments', grade:5, unit:3 },
  { id:'mi03', en:'drum',               ja:'ドラム',           emoji:'🥁', cat:'instruments', grade:5, unit:3 },
  { id:'mi04', en:'harmonica',          ja:'ハーモニカ',       emoji:'🎵', cat:'instruments', grade:5, unit:3 },
  { id:'mi05', en:'xylophone',          ja:'木琴・もっきん',   emoji:'🎵', cat:'instruments', grade:5, unit:3 },
  { id:'mi06', en:'triangle',           ja:'トライアングル',   emoji:'🔔', cat:'instruments', grade:5, unit:3 },
  { id:'mi07', en:'piano',              ja:'ピアノ',           emoji:'🎹', cat:'instruments', grade:5, unit:3 },
  { id:'mi08', en:'guitar',             ja:'ギター',           emoji:'🎸', cat:'instruments', grade:5, unit:3 },
  { id:'mi09', en:'keyboard harmonica', ja:'鍵盤ハーモニカ',   emoji:'🎹', cat:'instruments', grade:5, unit:3 },
  { id:'mi10', en:'flute',              ja:'フルート',         emoji:'🎵', cat:'instruments', grade:5, unit:3 },
  { id:'mi11', en:'trumpet',            ja:'トランペット',     emoji:'🎺', cat:'instruments', grade:5, unit:3 },
  { id:'mi12', en:'castanets',          ja:'カスタネット',     emoji:'🎶', cat:'instruments', grade:5, unit:3 },

  // ── EVERYDAY THINGS ───────────────────────────────────────────────────────
  { id:'th01', en:'bag',          ja:'かばん',     emoji:'👜', cat:'things', grade:5, unit:2 },
  { id:'th02', en:'umbrella',     ja:'かさ',       emoji:'☂️', cat:'things', grade:5, unit:2 },
  { id:'th03', en:'dictionary',   ja:'じしょ',     emoji:'📖', cat:'things', grade:5, unit:2 },
  { id:'th04', en:'watch',        ja:'とけい',     emoji:'⌚', cat:'things', grade:5, unit:2 },
  { id:'th05', en:'desk',         ja:'つくえ',     emoji:'🪑', cat:'things', grade:5, unit:2 },
  { id:'th06', en:'chair',        ja:'いす',       emoji:'🪑', cat:'things', grade:5, unit:2 },
  { id:'th07', en:'bed',          ja:'ベッド',     emoji:'🛏️', cat:'things', grade:5, unit:2 },
  { id:'th08', en:'computer',     ja:'コンピューター',emoji:'💻', cat:'things', grade:5, unit:2 },
  { id:'th09', en:'TV',           ja:'テレビ',     emoji:'📺', cat:'things', grade:5, unit:2 },
  { id:'th10', en:'smartphone',   ja:'スマートフォン',emoji:'📱', cat:'things', grade:5, unit:2 },
  { id:'th11', en:'tablet',       ja:'タブレット', emoji:'📱', cat:'things', grade:5, unit:2 },
  { id:'th12', en:'textbook',     ja:'きょうかしょ',emoji:'📚', cat:'things', grade:5, unit:2 },
  { id:'th13', en:'comic book',   ja:'マンガ',     emoji:'📔', cat:'things', grade:5, unit:2 },
  { id:'th14', en:'racket',       ja:'ラケット',   emoji:'🎾', cat:'things', grade:5, unit:2 },
  { id:'th15', en:'soccer shoes', ja:'サッカーシューズ',emoji:'👟', cat:'things', grade:5, unit:2 },
  { id:'th16', en:'ticket',       ja:'チケット',   emoji:'🎟️', cat:'things', grade:5, unit:2 },
  { id:'th17', en:'sticker',      ja:'シール',     emoji:'⭐', cat:'things', grade:5, unit:2 },
  { id:'th18', en:'glass',        ja:'コップ',     emoji:'🥛', cat:'things', grade:5, unit:2 },
  { id:'th19', en:'present',      ja:'プレゼント', emoji:'🎁', cat:'things', grade:5, unit:2 },
  { id:'th20', en:'treasure',     ja:'たからもの', emoji:'💎', cat:'things', grade:5, unit:2 },

  // ── EVENTS ────────────────────────────────────────────────────────────────
  { id:'ev01', en:'drama festival',       ja:'学芸会',       emoji:'🎭', cat:'events', grade:6, unit:3 },
  { id:'ev02', en:'field trip',           ja:'えんそく',     emoji:'🎒', cat:'events', grade:6, unit:3 },
  { id:'ev03', en:'music festival',       ja:'おんがくかい', emoji:'🎵', cat:'events', grade:6, unit:3 },
  { id:'ev04', en:'chorus contest',       ja:'合唱コンクール',emoji:'🎤', cat:'events', grade:6, unit:3 },
  { id:'ev05', en:'school trip',          ja:'しゅうがくりょこう',emoji:'🚌', cat:'events', grade:6, unit:3 },
  { id:'ev06', en:'sports day',           ja:'うんどうかい', emoji:'🏃', cat:'events', grade:6, unit:3 },
  { id:'ev07', en:'volunteer day',        ja:'ボランティアデー',emoji:'🤝', cat:'events', grade:6, unit:3 },
  { id:'ev08', en:'school festival',      ja:'がっこうさい', emoji:'🎉', cat:'events', grade:6, unit:3 },
  { id:'ev09', en:'swimming meet',        ja:'すいえいたいかい',emoji:'🏊', cat:'events', grade:6, unit:3 },
  { id:'ev10', en:'graduation ceremony',  ja:'そつぎょうしき',emoji:'🎓', cat:'events', grade:6, unit:3 },
  { id:'ev11', en:'entrance ceremony',    ja:'にゅうがくしき',emoji:'🌸', cat:'events', grade:6, unit:3 },
  { id:'ev12', en:'summer vacation',      ja:'なつやすみ',   emoji:'🏖️', cat:'events', grade:6, unit:3 },
  { id:'ev13', en:'birthday',             ja:'たんじょうび', emoji:'🎂', cat:'events', grade:5, unit:2 },
  { id:'ev14', en:'New Year\'s Day',      ja:'おしょうがつ', emoji:'🎍', cat:'events', grade:5, unit:0 },
  { id:'ev15', en:'Dolls\' Festival',     ja:'ひなまつり',   emoji:'🎎', cat:'events', grade:5, unit:0 },
  { id:'ev16', en:'Star Festival',        ja:'たなばた',     emoji:'🎋', cat:'events', grade:5, unit:0 },
  { id:'ev17', en:'Halloween',            ja:'ハロウィン',   emoji:'🎃', cat:'events', grade:5, unit:0 },
  { id:'ev18', en:'Christmas',            ja:'クリスマス',   emoji:'🎄', cat:'events', grade:5, unit:0 },
  { id:'ev19', en:'Children\'s Day',      ja:'こどもの日',   emoji:'🎏', cat:'events', grade:5, unit:0 },
  { id:'ev20', en:'Fireworks festival',   ja:'はなびたいかい',emoji:'🎆', cat:'events', grade:5, unit:0 },
  { id:'ev21', en:'cherry blossom viewing',ja:'お花見',      emoji:'🌸', cat:'events', grade:5, unit:0 },
  { id:'ev22', en:'New Year\'s Eve',      ja:'おおみそか',   emoji:'🎊', cat:'events', grade:5, unit:0 },

  // ── DESCRIPTIONS ──────────────────────────────────────────────────────────
  { id:'ds01', en:'good',         ja:'いい',       emoji:'👍', cat:'descriptions', grade:5, unit:4 },
  { id:'ds02', en:'great',        ja:'すごくいい', emoji:'🤩', cat:'descriptions', grade:5, unit:4 },
  { id:'ds03', en:'fantastic',    ja:'すばらしい', emoji:'🌟', cat:'descriptions', grade:6, unit:3 },
  { id:'ds04', en:'wonderful',    ja:'すてき',     emoji:'✨', cat:'descriptions', grade:6, unit:3 },
  { id:'ds05', en:'interesting',  ja:'おもしろい', emoji:'🤔', cat:'descriptions', grade:5, unit:1 },
  { id:'ds06', en:'beautiful',    ja:'うつくしい', emoji:'😍', cat:'descriptions', grade:6, unit:7 },
  { id:'ds07', en:'exciting',     ja:'わくわくする',emoji:'🎉', cat:'descriptions', grade:6, unit:3 },
  { id:'ds08', en:'fun',          ja:'たのしい',   emoji:'😄', cat:'descriptions', grade:5, unit:0 },
  { id:'ds09', en:'bad',          ja:'わるい',     emoji:'👎', cat:'descriptions', grade:5, unit:0 },
  { id:'ds10', en:'cool',         ja:'かっこいい', emoji:'😎', cat:'descriptions', grade:5, unit:4 },
  { id:'ds11', en:'nice',         ja:'すてき',     emoji:'😊', cat:'descriptions', grade:5, unit:4 },
  { id:'ds12', en:'famous',       ja:'ゆうめい',   emoji:'⭐', cat:'descriptions', grade:6, unit:0 },
  { id:'ds13', en:'popular',      ja:'にんきがある',emoji:'❤️', cat:'descriptions', grade:6, unit:0 },
  { id:'ds14', en:'cute',         ja:'かわいい',   emoji:'🥰', cat:'descriptions', grade:5, unit:0 },
  { id:'ds15', en:'amazing',      ja:'びっくりするような',emoji:'😲', cat:'descriptions', grade:6, unit:0 },
  { id:'ds16', en:'favorite',     ja:'お気に入りの',emoji:'❤️', cat:'descriptions', grade:5, unit:1 },
  { id:'ds17', en:'colorful',     ja:'カラフル',   emoji:'🌈', cat:'descriptions', grade:6, unit:3 },
  { id:'ds18', en:'international',ja:'こくさいてき',emoji:'🌍', cat:'descriptions', grade:6, unit:4 },
  { id:'ds19', en:'big',          ja:'おおきい',   emoji:'🐘', cat:'descriptions', grade:5, unit:0 },
  { id:'ds20', en:'small',        ja:'ちいさい',   emoji:'🐭', cat:'descriptions', grade:5, unit:0 },
  { id:'ds21', en:'high',         ja:'たかい',     emoji:'🏔️', cat:'descriptions', grade:6, unit:0 },
  { id:'ds22', en:'low',          ja:'ひくい',     emoji:'⬇️', cat:'descriptions', grade:6, unit:0 },
  { id:'ds23', en:'old',          ja:'ふるい',     emoji:'🏛️', cat:'descriptions', grade:6, unit:0 },
  { id:'ds24', en:'new',          ja:'あたらしい', emoji:'✨', cat:'descriptions', grade:6, unit:0 },
  { id:'ds25', en:'fast',         ja:'はやい',     emoji:'⚡', cat:'descriptions', grade:6, unit:0 },
  { id:'ds26', en:'slow',         ja:'おそい',     emoji:'🐢', cat:'descriptions', grade:6, unit:0 },
  { id:'ds27', en:'long',         ja:'ながい',     emoji:'📏', cat:'descriptions', grade:6, unit:0 },
  { id:'ds28', en:'short',        ja:'みじかい',   emoji:'📏', cat:'descriptions', grade:6, unit:0 },

  // ── JOBS ──────────────────────────────────────────────────────────────────
  { id:'jo01', en:'artist',         ja:'げいじゅつか',  emoji:'🎨', cat:'jobs', grade:5, unit:8 },
  { id:'jo02', en:'nurse',          ja:'かんごし',      emoji:'👩‍⚕️', cat:'jobs', grade:5, unit:8 },
  { id:'jo03', en:'farmer',         ja:'のうか',        emoji:'👨‍🌾', cat:'jobs', grade:5, unit:8 },
  { id:'jo04', en:'office worker',  ja:'かいしゃいん',  emoji:'💼', cat:'jobs', grade:5, unit:8 },
  { id:'jo05', en:'flight attendant',ja:'キャビンアテンダント',emoji:'✈️', cat:'jobs', grade:5, unit:8 },
  { id:'jo06', en:'writer',         ja:'さっか・ライター',emoji:'✍️', cat:'jobs', grade:5, unit:8 },
  { id:'jo07', en:'singer',         ja:'かしゅ',        emoji:'🎤', cat:'jobs', grade:5, unit:8 },
  { id:'jo08', en:'vet',            ja:'じゅうい',      emoji:'👨‍⚕️', cat:'jobs', grade:5, unit:8 },
  { id:'jo09', en:'police officer', ja:'けいさつかん',  emoji:'👮', cat:'jobs', grade:5, unit:8 },
  { id:'jo10', en:'astronaut',      ja:'うちゅうひこうし',emoji:'👨‍🚀', cat:'jobs', grade:5, unit:8 },
  { id:'jo11', en:'baseball player',ja:'やきゅうせんしゅ',emoji:'⚾', cat:'jobs', grade:5, unit:8 },
  { id:'jo12', en:'mountaineer',    ja:'とざんか',      emoji:'🧗', cat:'jobs', grade:5, unit:8 },
  { id:'jo13', en:'teacher',        ja:'せんせい',      emoji:'👩‍🏫', cat:'jobs', grade:5, unit:8 },
  { id:'jo14', en:'fire fighter',   ja:'しょうぼうし',  emoji:'👨‍🚒', cat:'jobs', grade:5, unit:8 },
  { id:'jo15', en:'zookeeper',      ja:'どうぶつえんのしいくがかり',emoji:'🦁', cat:'jobs', grade:5, unit:8 },
  { id:'jo16', en:'comedian',       ja:'お笑いタレント', emoji:'😂', cat:'jobs', grade:5, unit:8 },
  { id:'jo17', en:'pilot',          ja:'パイロット',    emoji:'✈️', cat:'jobs', grade:5, unit:8 },
  { id:'jo18', en:'cook',           ja:'コック・りょうりにん',emoji:'👨‍🍳', cat:'jobs', grade:5, unit:8 },
  { id:'jo19', en:'doctor',         ja:'いしゃ',        emoji:'👨‍⚕️', cat:'jobs', grade:5, unit:8 },
  { id:'jo20', en:'baker',          ja:'パンや',        emoji:'🥖', cat:'jobs', grade:5, unit:8 },
  { id:'jo21', en:'programmer',     ja:'プログラマー',  emoji:'💻', cat:'jobs', grade:5, unit:8 },
  { id:'jo22', en:'researcher',     ja:'けんきゅうしゃ', emoji:'🔬', cat:'jobs', grade:5, unit:8 },
  { id:'jo23', en:'scientist',      ja:'かがくしゃ',    emoji:'🧪', cat:'jobs', grade:5, unit:8 },

  // ── CLUBS & TEAMS ─────────────────────────────────────────────────────────
  { id:'cb01', en:'baseball team',       ja:'やきゅうぶ',   emoji:'⚾', cat:'clubs', grade:6, unit:8 },
  { id:'cb02', en:'soccer team',         ja:'サッカーぶ',   emoji:'⚽', cat:'clubs', grade:6, unit:8 },
  { id:'cb03', en:'tennis team',         ja:'テニスぶ',     emoji:'🎾', cat:'clubs', grade:6, unit:8 },
  { id:'cb04', en:'softball team',       ja:'ソフトボールぶ',emoji:'🥎', cat:'clubs', grade:6, unit:8 },
  { id:'cb05', en:'basketball team',     ja:'バスケットぶ', emoji:'🏀', cat:'clubs', grade:6, unit:8 },
  { id:'cb06', en:'volleyball team',     ja:'バレーボールぶ',emoji:'🏐', cat:'clubs', grade:6, unit:8 },
  { id:'cb07', en:'table tennis team',   ja:'たっきゅうぶ', emoji:'🏓', cat:'clubs', grade:6, unit:8 },
  { id:'cb08', en:'track and field team',ja:'りくじょうぶ', emoji:'🏃', cat:'clubs', grade:6, unit:8 },
  { id:'cb09', en:'badminton team',      ja:'バドミントンぶ',emoji:'🏸', cat:'clubs', grade:6, unit:8 },
  { id:'cb10', en:'dance team',          ja:'ダンスぶ',     emoji:'💃', cat:'clubs', grade:6, unit:8 },
  { id:'cb11', en:'brass band',          ja:'ブラスバンド・すいそうがくぶ',emoji:'🎺', cat:'clubs', grade:6, unit:8 },
  { id:'cb12', en:'chorus',              ja:'がっしょうぶ', emoji:'🎤', cat:'clubs', grade:6, unit:8 },
  { id:'cb13', en:'drama club',          ja:'えんげきぶ',   emoji:'🎭', cat:'clubs', grade:6, unit:8 },
  { id:'cb14', en:'photography club',    ja:'しゃしんぶ',   emoji:'📷', cat:'clubs', grade:6, unit:8 },
  { id:'cb15', en:'newspaper club',      ja:'しんぶんぶ',   emoji:'📰', cat:'clubs', grade:6, unit:8 },
  { id:'cb16', en:'art club',            ja:'びじゅつぶ',   emoji:'🎨', cat:'clubs', grade:6, unit:8 },
  { id:'cb17', en:'cooking club',        ja:'ちょうりぶ',   emoji:'🍳', cat:'clubs', grade:6, unit:8 },
  { id:'cb18', en:'broadcasting club',   ja:'ほうそうぶ',   emoji:'📻', cat:'clubs', grade:6, unit:8 },
];

// ── ROMAJI TABLE (Hepburn system, from p.48) ──────────────────────────────
const NH_ROMAJI = [
  // Vowels
  { kana:'あ', romaji:'a',   row:'vowels' }, { kana:'い', romaji:'i',   row:'vowels' },
  { kana:'う', romaji:'u',   row:'vowels' }, { kana:'え', romaji:'e',   row:'vowels' },
  { kana:'お', romaji:'o',   row:'vowels' },
  // K row
  { kana:'か', romaji:'ka',  row:'K' }, { kana:'き', romaji:'ki',  row:'K' },
  { kana:'く', romaji:'ku',  row:'K' }, { kana:'け', romaji:'ke',  row:'K' },
  { kana:'こ', romaji:'ko',  row:'K' }, { kana:'きゃ', romaji:'kya', row:'K' },
  { kana:'きゅ', romaji:'kyu', row:'K' }, { kana:'きょ', romaji:'kyo', row:'K' },
  // S row
  { kana:'さ', romaji:'sa',  row:'S' }, { kana:'し', romaji:'shi', row:'S' },
  { kana:'す', romaji:'su',  row:'S' }, { kana:'せ', romaji:'se',  row:'S' },
  { kana:'そ', romaji:'so',  row:'S' }, { kana:'しゃ', romaji:'sha', row:'S' },
  { kana:'しゅ', romaji:'shu', row:'S' }, { kana:'しょ', romaji:'sho', row:'S' },
  // T row
  { kana:'た', romaji:'ta',  row:'T' }, { kana:'ち', romaji:'chi', row:'T' },
  { kana:'つ', romaji:'tsu', row:'T' }, { kana:'て', romaji:'te',  row:'T' },
  { kana:'と', romaji:'to',  row:'T' }, { kana:'ちゃ', romaji:'cha', row:'T' },
  { kana:'ちゅ', romaji:'chu', row:'T' }, { kana:'ちょ', romaji:'cho', row:'T' },
  // N row
  { kana:'な', romaji:'na',  row:'N' }, { kana:'に', romaji:'ni',  row:'N' },
  { kana:'ぬ', romaji:'nu',  row:'N' }, { kana:'ね', romaji:'ne',  row:'N' },
  { kana:'の', romaji:'no',  row:'N' }, { kana:'にゃ', romaji:'nya', row:'N' },
  { kana:'にゅ', romaji:'nyu', row:'N' }, { kana:'にょ', romaji:'nyo', row:'N' },
  // H row
  { kana:'は', romaji:'ha',  row:'H' }, { kana:'ひ', romaji:'hi',  row:'H' },
  { kana:'ふ', romaji:'fu',  row:'H' }, { kana:'へ', romaji:'he',  row:'H' },
  { kana:'ほ', romaji:'ho',  row:'H' }, { kana:'ひゃ', romaji:'hya', row:'H' },
  { kana:'ひゅ', romaji:'hyu', row:'H' }, { kana:'ひょ', romaji:'hyo', row:'H' },
  // M row
  { kana:'ま', romaji:'ma',  row:'M' }, { kana:'み', romaji:'mi',  row:'M' },
  { kana:'む', romaji:'mu',  row:'M' }, { kana:'め', romaji:'me',  row:'M' },
  { kana:'も', romaji:'mo',  row:'M' }, { kana:'みゃ', romaji:'mya', row:'M' },
  { kana:'みゅ', romaji:'myu', row:'M' }, { kana:'みょ', romaji:'myo', row:'M' },
  // Y row
  { kana:'や', romaji:'ya',  row:'Y' }, { kana:'ゆ', romaji:'yu',  row:'Y' },
  { kana:'よ', romaji:'yo',  row:'Y' },
  // R row
  { kana:'ら', romaji:'ra',  row:'R' }, { kana:'り', romaji:'ri',  row:'R' },
  { kana:'る', romaji:'ru',  row:'R' }, { kana:'れ', romaji:'re',  row:'R' },
  { kana:'ろ', romaji:'ro',  row:'R' }, { kana:'りゃ', romaji:'rya', row:'R' },
  { kana:'りゅ', romaji:'ryu', row:'R' }, { kana:'りょ', romaji:'ryo', row:'R' },
  // W row
  { kana:'わ', romaji:'wa',  row:'W' },
  // N
  { kana:'ん', romaji:'n',   row:'N_' },
  // G row
  { kana:'が', romaji:'ga',  row:'G' }, { kana:'ぎ', romaji:'gi',  row:'G' },
  { kana:'ぐ', romaji:'gu',  row:'G' }, { kana:'げ', romaji:'ge',  row:'G' },
  { kana:'ご', romaji:'go',  row:'G' }, { kana:'ぎゃ', romaji:'gya', row:'G' },
  { kana:'ぎゅ', romaji:'gyu', row:'G' }, { kana:'ぎょ', romaji:'gyo', row:'G' },
  // Z row
  { kana:'ざ', romaji:'za',  row:'Z' }, { kana:'じ', romaji:'ji',  row:'Z' },
  { kana:'ず', romaji:'zu',  row:'Z' }, { kana:'ぜ', romaji:'ze',  row:'Z' },
  { kana:'ぞ', romaji:'zo',  row:'Z' }, { kana:'じゃ', romaji:'ja',  row:'Z' },
  { kana:'じゅ', romaji:'ju',  row:'Z' }, { kana:'じょ', romaji:'jo',  row:'Z' },
  // D row
  { kana:'だ', romaji:'da',  row:'D' }, { kana:'で', romaji:'de',  row:'D' },
  { kana:'ど', romaji:'do',  row:'D' },
  // B row
  { kana:'ば', romaji:'ba',  row:'B' }, { kana:'び', romaji:'bi',  row:'B' },
  { kana:'ぶ', romaji:'bu',  row:'B' }, { kana:'べ', romaji:'be',  row:'B' },
  { kana:'ぼ', romaji:'bo',  row:'B' }, { kana:'びゃ', romaji:'bya', row:'B' },
  { kana:'びゅ', romaji:'byu', row:'B' }, { kana:'びょ', romaji:'byo', row:'B' },
  // P row
  { kana:'ぱ', romaji:'pa',  row:'P' }, { kana:'ぴ', romaji:'pi',  row:'P' },
  { kana:'ぷ', romaji:'pu',  row:'P' }, { kana:'ぺ', romaji:'pe',  row:'P' },
  { kana:'ぽ', romaji:'po',  row:'P' }, { kana:'ぴゃ', romaji:'pya', row:'P' },
  { kana:'ぴゅ', romaji:'pyu', row:'P' }, { kana:'ぴょ', romaji:'pyo', row:'P' },
];
