// kanken3-content.js — 原作の練習コンテンツバンク（漢検3級 出題範囲準拠）
//
// ここに収めた語・四字熟語・対義語/類義語・送り仮名・同音異字・部首の各データは
// すべて本モジュールのために書き起こした独自コンテンツで、協会の過去問題文は
// 一切複製していない（過去問の著作権は協会に帰属するため）。用いる漢字はすべて
// 3級までの配当（累計1623字）に収まることを、協会準拠のレベル表で機械的に検証
// 済み。3級配当漢字を含む語には、その字の読みが KANJIDIC の音訓と整合することも
// 自動照合した。生成側（kanken3-generators.js）はこのデータから毎回問題を作る。
const KANKEN3_CONTENT = {
  koseiLabels: {
    similar: '同じような意味の漢字を重ねたもの',
    opposite: '反対または対応の意味を表す字を重ねたもの',
    modifier: '上の字が下の字を修飾しているもの',
    object: '下の字が上の字の目的語・補語になっているもの',
    negation: '上の字が下の字の意味を打ち消しているもの',
  },
  words: [
    {w:'湿潤', r:'しつじゅん', kosei:'similar'},
    {w:'遭遇', r:'そうぐう', kosei:'similar'},
    {w:'崩壊', r:'ほうかい', kosei:'similar'},
    {w:'邪悪', r:'じゃあく', kosei:'similar'},
    {w:'賢明', r:'けんめい', kosei:'similar'},
    {w:'削減', r:'さくげん', kosei:'similar'},
    {w:'墳墓', r:'ふんぼ', kosei:'similar'},
    {w:'陳列', r:'ちんれつ', kosei:'similar'},
    {w:'悦楽', r:'えつらく', kosei:'similar'},
    {w:'隔離', r:'かくり', kosei:'similar'},
    {w:'誘導', r:'ゆうどう', kosei:'similar'},
    {w:'征伐', r:'せいばつ', kosei:'similar'},
    {w:'鍛錬', r:'たんれん', kosei:'similar'},
    {w:'携帯', r:'けいたい', kosei:'similar'},
    {w:'緩和', r:'かんわ', kosei:'similar'},
    {w:'賢愚', r:'けんぐ', kosei:'opposite'},
    {w:'昇降', r:'しょうこう', kosei:'opposite'},
    {w:'起伏', r:'きふく', kosei:'opposite'},
    {w:'抑揚', r:'よくよう', kosei:'opposite'},
    {w:'攻防', r:'こうぼう', kosei:'opposite'},
    {w:'邦画', r:'ほうが', kosei:'modifier'},
    {w:'陶器', r:'とうき', kosei:'modifier'},
    {w:'硬貨', r:'こうか', kosei:'modifier'},
    {w:'猟犬', r:'りょうけん', kosei:'modifier'},
    {w:'胎児', r:'たいじ', kosei:'modifier'},
    {w:'滝口', r:'たきぐち', kosei:'modifier'},
    {w:'晩鐘', r:'ばんしょう', kosei:'modifier'},
    {w:'鶏舎', r:'けいしゃ', kosei:'modifier'},
    {w:'慕情', r:'ぼじょう', kosei:'modifier'},
    {w:'遭難', r:'そうなん', kosei:'object'},
    {w:'免税', r:'めんぜい', kosei:'object'},
    {w:'排水', r:'はいすい', kosei:'object'},
    {w:'慰霊', r:'いれい', kosei:'object'},
    {w:'駐車', r:'ちゅうしゃ', kosei:'object'},
    {w:'募金', r:'ぼきん', kosei:'object'},
    {w:'架橋', r:'かきょう', kosei:'object'},
    {w:'避難', r:'ひなん', kosei:'object'},
    {w:'未遂', r:'みすい', kosei:'negation'},
    {w:'不振', r:'ふしん', kosei:'negation'},
    {w:'無比', r:'むひ', kosei:'negation'},
    {w:'未熟', r:'みじゅく', kosei:'negation'},
    {w:'非凡', r:'ひぼん', kosei:'negation'},
    {w:'無恥', r:'むち', kosei:'negation'},
  ],
  pairs: [
    {a:'偉大', ar:'いだい', b:'卑小', br:'ひしょう', rel:'antonym'},
    {a:'分裂', ar:'ぶんれつ', b:'統一', br:'とういつ', rel:'antonym'},
    {a:'削除', ar:'さくじょ', b:'添加', br:'てんか', rel:'antonym'},
    {a:'濫用', ar:'らんよう', b:'節約', br:'せつやく', rel:'antonym'},
    {a:'拡大', ar:'かくだい', b:'縮小', br:'しゅくしょう', rel:'antonym'},
    {a:'抽象', ar:'ちゅうしょう', b:'具体', br:'ぐたい', rel:'antonym'},
    {a:'前進', ar:'ぜんしん', b:'後退', br:'こうたい', rel:'antonym'},
    {a:'卓越', ar:'たくえつ', b:'抜群', br:'ばつぐん', rel:'synonym'},
    {a:'永遠', ar:'えいえん', b:'永久', br:'えいきゅう', rel:'synonym'},
    {a:'冷静', ar:'れいせい', b:'沈着', br:'ちんちゃく', rel:'synonym'},
    {a:'模範', ar:'もはん', b:'手本', br:'てほん', rel:'synonym'},
    {a:'突然', ar:'とつぜん', b:'不意', br:'ふい', rel:'synonym'},
    {a:'綱領', ar:'こうりょう', b:'方針', br:'ほうしん', rel:'synonym'},
    {a:'憶測', ar:'おくそく', b:'推量', br:'すいりょう', rel:'synonym'},
  ],
  yoji: [
    {w:'一喜一憂', r:'いっきいちゆう', gloss:'喜んだり心配したり気持ちが変わること', blank:3, ans:'憂'},
    {w:'無我夢中', r:'むがむちゅう', gloss:'我を忘れて物事に熱中すること', blank:2, ans:'夢'},
    {w:'油断大敵', r:'ゆだんたいてき', gloss:'油断は失敗のもとで恐ろしいということ', blank:3, ans:'敵'},
    {w:'自画自賛', r:'じがじさん', gloss:'自分で自分をほめること', blank:3, ans:'賛'},
    {w:'一部始終', r:'いちぶしじゅう', gloss:'物事の始めから終わりまで全部', blank:3, ans:'終'},
    {w:'公明正大', r:'こうめいせいだい', gloss:'私心がなく公正なこと', blank:0, ans:'公'},
    {w:'半信半疑', r:'はんしんはんぎ', gloss:'半分信じ半分疑うこと', blank:3, ans:'疑'},
    {w:'針小棒大', r:'しんしょうぼうだい', gloss:'小さな事を大げさに言うこと', blank:0, ans:'針'},
    {w:'異口同音', r:'いくどうおん', gloss:'多くの人が口をそろえて同じことを言うこと', blank:2, ans:'同'},
    {w:'危機一髪', r:'ききいっぱつ', gloss:'あぶないせとぎわ', blank:1, ans:'機'},
    {w:'絶体絶命', r:'ぜったいぜつめい', gloss:'どうにも逃れられない苦しい立場', blank:2, ans:'絶'},
    {w:'率先垂範', r:'そっせんすいはん', gloss:'人の先に立って手本を示すこと', blank:3, ans:'範'},
    {w:'複雑怪奇', r:'ふくざつかいき', gloss:'こみいっていて怪しくふしぎなこと', blank:2, ans:'怪'},
    {w:'質疑応答', r:'しつぎおうとう', gloss:'問いと答えをやりとりすること', blank:1, ans:'疑'},
  ],
  okuri: [
    {r:'なぐさめる', stem:'慰', split:3, gloss:'つらい人の心をやわらげる'},
    {r:'うるおう', stem:'潤', split:3, gloss:'水気をふくむ・恵まれる'},
    {r:'なめらか', stem:'滑', split:2, gloss:'つるつるしている'},
    {r:'おだやか', stem:'穏', split:2, gloss:'静かで落ち着いている'},
    {r:'あぶない', stem:'危', split:2, gloss:'あぶない'},
    {r:'うらむ', stem:'恨', split:2, gloss:'にくく思う気持ちをもち続ける'},
    {r:'うながす', stem:'促', split:3, gloss:'早くするように仕向ける'},
    {r:'にくらしい', stem:'憎', split:2, gloss:'にくいと感じる'},
    {r:'なまける', stem:'怠', split:2, gloss:'するべきことをしない'},
    {r:'あざやか', stem:'鮮', split:2, gloss:'色や技がはっきり見事だ'},
    {r:'あわただしい', stem:'慌', split:2, gloss:'せわしなく落ち着かない'},
    {r:'さそう', stem:'誘', split:2, gloss:'いっしょにするように勧める'},
    {r:'うれえる', stem:'憂', split:2, gloss:'心配する'},
    {r:'しずまる', stem:'鎮', split:2, gloss:'さわぎや痛みがおさまる'},
  ],
  doon: [
    {read:'コウ', phrase:'◯外に出かける', ans:'郊', dis:['甲','孔','絞']},
    {read:'カン', phrase:'習◯を身につける', ans:'慣', dis:['肝','冠','勘']},
    {read:'ショウ', phrase:'機械が故◯する', ans:'障', dis:['焦','掌','鐘']},
    {read:'ソウ', phrase:'部屋を◯除する', ans:'掃', dis:['桑','双','葬']},
    {read:'チュウ', phrase:'駅前に◯車する', ans:'駐', dis:['鋳','抽','宙']},
    {read:'ボウ', phrase:'危険を◯止する', ans:'防', dis:['妨','某','膨']},
  ],
  bushu: [
    {k:'詠', rad:'言', name:'ごんべん'},
    {k:'慰', rad:'心', name:'こころ'},
    {k:'炎', rad:'火', name:'ひ'},
    {k:'宴', rad:'宀', name:'うかんむり'},
    {k:'欧', rad:'欠', name:'あくび'},
    {k:'殴', rad:'殳', name:'るまた'},
    {k:'穏', rad:'禾', name:'のぎへん'},
    {k:'架', rad:'木', name:'き'},
    {k:'嫁', rad:'女', name:'おんなへん'},
    {k:'怪', rad:'忄', name:'りっしんべん'},
    {k:'該', rad:'言', name:'ごんべん'},
    {k:'掛', rad:'扌', name:'てへん'},
    {k:'貫', rad:'貝', name:'かい'},
    {k:'喚', rad:'口', name:'くちへん'},
    {k:'緩', rad:'糸', name:'いとへん'},
    {k:'軌', rad:'車', name:'くるまへん'},
    {k:'騎', rad:'馬', name:'うまへん'},
    {k:'菊', rad:'艹', name:'くさかんむり'},
    {k:'峡', rad:'山', name:'やまへん'},
    {k:'凝', rad:'冫', name:'にすい'},
    {k:'刑', rad:'刂', name:'りっとう'},
    {k:'掲', rad:'扌', name:'てへん'},
    {k:'鶏', rad:'鳥', name:'とり'},
    {k:'鯨', rad:'魚', name:'うおへん'},
    {k:'賢', rad:'貝', name:'かい'},
    {k:'弧', rad:'弓', name:'ゆみへん'},
    {k:'雇', rad:'隹', name:'ふるとり'},
    {k:'顧', rad:'頁', name:'おおがい'},
    {k:'孔', rad:'子', name:'こへん'},
    {k:'硬', rad:'石', name:'いしへん'},
    {k:'酵', rad:'酉', name:'とりへん'},
    {k:'恨', rad:'忄', name:'りっしんべん'},
    {k:'魂', rad:'鬼', name:'おに'},
    {k:'債', rad:'亻', name:'にんべん'},
    {k:'祉', rad:'礻', name:'しめすへん'},
    {k:'疾', rad:'疒', name:'やまいだれ'},
    {k:'赦', rad:'赤', name:'あか'},
    {k:'殊', rad:'歹', name:'がつへん'},
    {k:'遂', rad:'辶', name:'しんにょう'},
    {k:'髄', rad:'骨', name:'ほねへん'},
    {k:'籍', rad:'竹', name:'たけかんむり'},
    {k:'潜', rad:'氵', name:'さんずい'},
    {k:'掃', rad:'扌', name:'てへん'},
    {k:'賊', rad:'貝', name:'かい'},
    {k:'胎', rad:'月', name:'にくづき'},
    {k:'鍛', rad:'金', name:'かねへん'},
    {k:'窒', rad:'穴', name:'あなかんむり'},
    {k:'彫', rad:'彡', name:'さんづくり'},
    {k:'聴', rad:'耳', name:'みみへん'},
    {k:'帝', rad:'巾', name:'はば'},
    {k:'篤', rad:'竹', name:'たけかんむり'},
    {k:'豚', rad:'豕', name:'いのこ'},
    {k:'尿', rad:'尸', name:'しかばね'},
    {k:'婆', rad:'女', name:'おんな'},
    {k:'帆', rad:'巾', name:'はばへん'},
    {k:'蛮', rad:'虫', name:'むし'},
    {k:'碑', rad:'石', name:'いしへん'},
    {k:'赴', rad:'走', name:'そうにょう'},
    {k:'符', rad:'竹', name:'たけかんむり'},
    {k:'覆', rad:'襾', name:'おおいかんむり'},
    {k:'墳', rad:'土', name:'つちへん'},
    {k:'癖', rad:'疒', name:'やまいだれ'},
    {k:'簿', rad:'竹', name:'たけかんむり'},
    {k:'崩', rad:'山', name:'やまへん'},
    {k:'翻', rad:'羽', name:'はね'},
    {k:'魅', rad:'鬼', name:'おに'},
    {k:'幽', rad:'幺', name:'いとがしら'},
    {k:'擁', rad:'扌', name:'てへん'},
    {k:'裸', rad:'衤', name:'ころもへん'},
    {k:'零', rad:'雨', name:'あめかんむり'},
    {k:'廉', rad:'广', name:'まだれ'},
    {k:'炉', rad:'火', name:'ひへん'},
    {k:'楼', rad:'木', name:'きへん'},
    {k:'湾', rad:'氵', name:'さんずい'},
  ],
};
if (typeof module !== 'undefined') { module.exports = { KANKEN3_CONTENT }; }
