// kanken3-content.js — 原作の練習コンテンツバンク（漢検3級 出題範囲準拠）
//
// 収録データ（語・四字熟語・対義語/類義語・送り仮名・同音異字・漢字識別・
// 誤字訂正・部首）はすべて本モジュール用に書き起こした独自コンテンツで、
// 協会の過去問題文は一切複製していない（過去問の著作権は協会に帰属）。用いる
// 漢字はすべて3級までの配当（累計1623字）に収まることを協会準拠のレベル表で
// 機械検証し、3級配当漢字を含む語はその読みが KANJIDIC の音訓と整合すること、
// 二字熟語の全読みが一意であること（書き取りの一意性）も自動照合済み。生成側
// （kanken3-generators.js）はこのデータから毎回問題を作る。
const KANKEN3_CONTENT = {
  koseiLabels: {
    similar: '同じような意味の漢字を重ねたもの',
    opposite: '反対または対応の意味を表す字を重ねたもの',
    modifier: '上の字が下の字を修飾しているもの',
    object: '下の字が上の字の目的語・補語になっているもの',
    negation: '上の字が下の字の意味を打ち消しているもの',
  },
  words: [
    {w:'湿潤', r:'しつじゅん', kosei:'similar'},
    {w:'遭遇', r:'そうぐう', kosei:'similar'},
    {w:'崩壊', r:'ほうかい', kosei:'similar'},
    {w:'邪悪', r:'じゃあく', kosei:'similar'},
    {w:'賢明', r:'けんめい', kosei:'similar'},
    {w:'削減', r:'さくげん', kosei:'similar'},
    {w:'墳墓', r:'ふんぼ', kosei:'similar'},
    {w:'陳列', r:'ちんれつ', kosei:'similar'},
    {w:'悦楽', r:'えつらく', kosei:'similar'},
    {w:'隔離', r:'かくり', kosei:'similar'},
    {w:'誘導', r:'ゆうどう', kosei:'similar'},
    {w:'征伐', r:'せいばつ', kosei:'similar'},
    {w:'鍛錬', r:'たんれん', kosei:'similar'},
    {w:'携帯', r:'けいたい', kosei:'similar'},
    {w:'緩和', r:'かんわ', kosei:'similar'},
    {w:'卑劣', r:'ひれつ', kosei:'similar'},
    {w:'華麗', r:'かれい', kosei:'similar'},
    {w:'隆盛', r:'りゅうせい', kosei:'similar'},
    {w:'阻害', r:'そがい', kosei:'similar'},
    {w:'抑圧', r:'よくあつ', kosei:'similar'},
    {w:'掌握', r:'しょうあく', kosei:'similar'},
    {w:'譲渡', r:'じょうと', kosei:'similar'},
    {w:'円滑', r:'えんかつ', kosei:'similar'},
    {w:'潤沢', r:'じゅんたく', kosei:'similar'},
    {w:'促進', r:'そくしん', kosei:'similar'},
    {w:'犠牲', r:'ぎせい', kosei:'similar'},
    {w:'卑屈', r:'ひくつ', kosei:'similar'},
    {w:'概略', r:'がいりゃく', kosei:'similar'},
    {w:'掃討', r:'そうとう', kosei:'similar'},
    {w:'墜落', r:'ついらく', kosei:'similar'},
    {w:'賢愚', r:'けんぐ', kosei:'opposite'},
    {w:'昇降', r:'しょうこう', kosei:'opposite'},
    {w:'起伏', r:'きふく', kosei:'opposite'},
    {w:'抑揚', r:'よくよう', kosei:'opposite'},
    {w:'攻防', r:'こうぼう', kosei:'opposite'},
    {w:'添削', r:'てんさく', kosei:'opposite'},
    {w:'屈伸', r:'くっしん', kosei:'opposite'},
    {w:'緩急', r:'かんきゅう', kosei:'opposite'},
    {w:'邦画', r:'ほうが', kosei:'modifier'},
    {w:'陶器', r:'とうき', kosei:'modifier'},
    {w:'硬貨', r:'こうか', kosei:'modifier'},
    {w:'猟犬', r:'りょうけん', kosei:'modifier'},
    {w:'胎児', r:'たいじ', kosei:'modifier'},
    {w:'滝口', r:'たきぐち', kosei:'modifier'},
    {w:'晩鐘', r:'ばんしょう', kosei:'modifier'},
    {w:'鶏舎', r:'けいしゃ', kosei:'modifier'},
    {w:'慕情', r:'ぼじょう', kosei:'modifier'},
    {w:'陶芸', r:'とうげい', kosei:'modifier'},
    {w:'邦楽', r:'ほうがく', kosei:'modifier'},
    {w:'硬球', r:'こうきゅう', kosei:'modifier'},
    {w:'幽谷', r:'ゆうこく', kosei:'modifier'},
    {w:'邪道', r:'じゃどう', kosei:'modifier'},
    {w:'佳作', r:'かさく', kosei:'modifier'},
    {w:'華道', r:'かどう', kosei:'modifier'},
    {w:'稚魚', r:'ちぎょ', kosei:'modifier'},
    {w:'苗床', r:'なえどこ', kosei:'modifier'},
    {w:'帆船', r:'はんせん', kosei:'modifier'},
    {w:'炉端', r:'ろばた', kosei:'modifier'},
    {w:'墨絵', r:'すみえ', kosei:'modifier'},
    {w:'藩主', r:'はんしゅ', kosei:'modifier'},
    {w:'猟師', r:'りょうし', kosei:'modifier'},
    {w:'濫読', r:'らんどく', kosei:'modifier'},
    {w:'遭難', r:'そうなん', kosei:'object'},
    {w:'免税', r:'めんぜい', kosei:'object'},
    {w:'排水', r:'はいすい', kosei:'object'},
    {w:'慰霊', r:'いれい', kosei:'object'},
    {w:'駐車', r:'ちゅうしゃ', kosei:'object'},
    {w:'募金', r:'ぼきん', kosei:'object'},
    {w:'架橋', r:'かきょう', kosei:'object'},
    {w:'避難', r:'ひなん', kosei:'object'},
    {w:'遂行', r:'すいこう', kosei:'similar'},
    {w:'惜別', r:'せきべつ', kosei:'object'},
    {w:'排気', r:'はいき', kosei:'object'},
    {w:'譲位', r:'じょうい', kosei:'object'},
    {w:'潜水', r:'せんすい', kosei:'object'},
    {w:'徐行', r:'じょこう', kosei:'modifier'},
    {w:'邪推', r:'じゃすい', kosei:'modifier'},
    {w:'未遂', r:'みすい', kosei:'negation'},
    {w:'不振', r:'ふしん', kosei:'negation'},
    {w:'無比', r:'むひ', kosei:'negation'},
    {w:'未熟', r:'みじゅく', kosei:'negation'},
    {w:'非凡', r:'ひぼん', kosei:'negation'},
    {w:'無恥', r:'むち', kosei:'negation'},
    {w:'無謀', r:'むぼう', kosei:'negation'},
    {w:'未定', r:'みてい', kosei:'negation'},
    {w:'不屈', r:'ふくつ', kosei:'negation'},
  ],
  pairs: [
    {a:'偉大', ar:'いだい', b:'卑小', br:'ひしょう', rel:'antonym'},
    {a:'分裂', ar:'ぶんれつ', b:'統一', br:'とういつ', rel:'antonym'},
    {a:'削除', ar:'さくじょ', b:'添加', br:'てんか', rel:'antonym'},
    {a:'濫用', ar:'らんよう', b:'節約', br:'せつやく', rel:'antonym'},
    {a:'拡大', ar:'かくだい', b:'縮小', br:'しゅくしょう', rel:'antonym'},
    {a:'抽象', ar:'ちゅうしょう', b:'具体', br:'ぐたい', rel:'antonym'},
    {a:'前進', ar:'ぜんしん', b:'後退', br:'こうたい', rel:'antonym'},
    {a:'生産', ar:'せいさん', b:'消費', br:'しょうひ', rel:'antonym'},
    {a:'楽観', ar:'らっかん', b:'悲観', br:'ひかん', rel:'antonym'},
    {a:'積極', ar:'せっきょく', b:'消極', br:'しょうきょく', rel:'antonym'},
    {a:'一般', ar:'いっぱん', b:'特殊', br:'とくしゅ', rel:'antonym'},
    {a:'単純', ar:'たんじゅん', b:'複雑', br:'ふくざつ', rel:'antonym'},
    {a:'直接', ar:'ちょくせつ', b:'間接', br:'かんせつ', rel:'antonym'},
    {a:'温暖', ar:'おんだん', b:'寒冷', br:'かんれい', rel:'antonym'},
    {a:'収入', ar:'しゅうにゅう', b:'支出', br:'ししゅつ', rel:'antonym'},
    {a:'華美', ar:'かび', b:'質素', br:'しっそ', rel:'antonym'},
    {a:'記憶', ar:'きおく', b:'忘却', br:'ぼうきゃく', rel:'antonym'},
    {a:'加入', ar:'かにゅう', b:'脱退', br:'だったい', rel:'antonym'},
    {a:'卓越', ar:'たくえつ', b:'抜群', br:'ばつぐん', rel:'synonym'},
    {a:'永遠', ar:'えいえん', b:'永久', br:'えいきゅう', rel:'synonym'},
    {a:'冷静', ar:'れいせい', b:'沈着', br:'ちんちゃく', rel:'synonym'},
    {a:'模範', ar:'もはん', b:'手本', br:'てほん', rel:'synonym'},
    {a:'突然', ar:'とつぜん', b:'不意', br:'ふい', rel:'synonym'},
    {a:'綱領', ar:'こうりょう', b:'方針', br:'ほうしん', rel:'synonym'},
    {a:'憶測', ar:'おくそく', b:'推量', br:'すいりょう', rel:'synonym'},
    {a:'我慢', ar:'がまん', b:'辛抱', br:'しんぼう', rel:'synonym'},
    {a:'束縛', ar:'そくばく', b:'拘束', br:'こうそく', rel:'synonym'},
    {a:'賛成', ar:'さんせい', b:'同意', br:'どうい', rel:'synonym'},
    {a:'進歩', ar:'しんぽ', b:'向上', br:'こうじょう', rel:'synonym'},
    {a:'欠点', ar:'けってん', b:'短所', br:'たんしょ', rel:'synonym'},
    {a:'準備', ar:'じゅんび', b:'用意', br:'ようい', rel:'synonym'},
    {a:'有名', ar:'ゆうめい', b:'著名', br:'ちょめい', rel:'synonym'},
    {a:'対等', ar:'たいとう', b:'互角', br:'ごかく', rel:'synonym'},
    {a:'律儀', ar:'りちぎ', b:'実直', br:'じっちょく', rel:'synonym'},
  ],
  yoji: [
    {w:'一喜一憂', r:'いっきいちゆう', gloss:'喜んだり心配したり気持ちが変わること', blank:3, ans:'憂'},
    {w:'無我夢中', r:'むがむちゅう', gloss:'我を忘れて物事に熱中すること', blank:2, ans:'夢'},
    {w:'油断大敵', r:'ゆだんたいてき', gloss:'油断は失敗のもとで恐ろしいということ', blank:3, ans:'敵'},
    {w:'自画自賛', r:'じがじさん', gloss:'自分で自分をほめること', blank:3, ans:'賛'},
    {w:'一部始終', r:'いちぶしじゅう', gloss:'物事の始めから終わりまで全部', blank:3, ans:'終'},
    {w:'公明正大', r:'こうめいせいだい', gloss:'私心がなく公正なこと', blank:0, ans:'公'},
    {w:'半信半疑', r:'はんしんはんぎ', gloss:'半分信じ半分疑うこと', blank:3, ans:'疑'},
    {w:'針小棒大', r:'しんしょうぼうだい', gloss:'小さな事を大げさに言うこと', blank:0, ans:'針'},
    {w:'異口同音', r:'いくどうおん', gloss:'多くの人が口をそろえて同じことを言うこと', blank:2, ans:'同'},
    {w:'危機一髪', r:'ききいっぱつ', gloss:'あぶないせとぎわ', blank:1, ans:'機'},
    {w:'絶体絶命', r:'ぜったいぜつめい', gloss:'どうにも逃れられない苦しい立場', blank:2, ans:'絶'},
    {w:'率先垂範', r:'そっせんすいはん', gloss:'人の先に立って手本を示すこと', blank:3, ans:'範'},
    {w:'複雑怪奇', r:'ふくざつかいき', gloss:'こみいっていて怪しくふしぎなこと', blank:2, ans:'怪'},
    {w:'質疑応答', r:'しつぎおうとう', gloss:'問いと答えをやりとりすること', blank:1, ans:'疑'},
    {w:'一石二鳥', r:'いっせきにちょう', gloss:'一つの行いで二つの利益を得ること', blank:1, ans:'石'},
    {w:'温故知新', r:'おんこちしん', gloss:'昔のことを研究して新しい知識を得ること', blank:1, ans:'故'},
    {w:'心機一転', r:'しんきいってん', gloss:'あることをきっかけに気持ちがすっかり変わること', blank:1, ans:'機'},
    {w:'単刀直入', r:'たんとうちょくにゅう', gloss:'前置きなしにいきなり本題に入ること', blank:0, ans:'単'},
    {w:'用意周到', r:'よういしゅうとう', gloss:'準備が行き届いて手ぬかりのないこと', blank:2, ans:'周'},
    {w:'意味深長', r:'いみしんちょう', gloss:'表面の意味の奥に深い意味があること', blank:2, ans:'深'},
    {w:'大同小異', r:'だいどうしょうい', gloss:'細かい違いはあるが大体は同じであること', blank:3, ans:'異'},
    {w:'我田引水', r:'がでんいんすい', gloss:'自分に都合のよいように言ったり行ったりすること', blank:1, ans:'田'},
    {w:'一進一退', r:'いっしんいったい', gloss:'進んだり退いたりして情勢が定まらないこと', blank:3, ans:'退'},
    {w:'起承転結', r:'きしょうてんけつ', gloss:'物事や文章の組み立ての順序', blank:2, ans:'転'},
    {w:'空前絶後', r:'くうぜんぜつご', gloss:'過去にも将来にも例がないほど珍しいこと', blank:2, ans:'絶'},
    {w:'完全無欠', r:'かんぜんむけつ', gloss:'足りないところがなく完全なこと', blank:3, ans:'欠'},
    {w:'臨機応変', r:'りんきおうへん', gloss:'その場に応じて適切に処理すること', blank:3, ans:'変'},
    {w:'疑心暗鬼', r:'ぎしんあんき', gloss:'うたがい出すと何でも不安に思えること', blank:3, ans:'鬼'},
    {w:'意気投合', r:'いきとうごう', gloss:'たがいの気持ちがぴったり合うこと', blank:2, ans:'投'},
    {w:'前代未聞', r:'ぜんだいみもん', gloss:'今までに聞いたこともない珍しいこと', blank:2, ans:'未'},
    {w:'千差万別', r:'せんさばんべつ', gloss:'さまざまで違いが多いこと', blank:1, ans:'差'},
    {w:'一朝一夕', r:'いっちょういっせき', gloss:'わずかの時間・短い期間', blank:3, ans:'夕'},
    {w:'有名無実', r:'ゆうめいむじつ', gloss:'名ばかりで中身がともなわないこと', blank:2, ans:'無'},
    {w:'起死回生', r:'きしかいせい', gloss:'絶望的な状態を一気に立て直すこと', blank:2, ans:'回'},
    {w:'因果応報', r:'いんがおうほう', gloss:'よい行いにはよい報い、悪い行いには悪い報いがあること', blank:0, ans:'因'},
    {w:'支離滅裂', r:'しりめつれつ', gloss:'ばらばらで筋道が立たないこと', blank:3, ans:'裂'},
    {w:'平身低頭', r:'へいしんていとう', gloss:'ひたすらおそれいってわびること', blank:2, ans:'低'},
    {w:'縦横無尽', r:'じゅうおうむじん', gloss:'自由自在に思う存分ふるまうこと', blank:3, ans:'尽'},
    {w:'悪戦苦闘', r:'あくせんくとう', gloss:'困難な中で苦しみながら努力すること', blank:3, ans:'闘'},
    {w:'傍若無人', r:'ぼうじゃくぶじん', gloss:'人前をはばからず勝手にふるまうこと', blank:1, ans:'若'},
  ],
  okuri: [
    {r:'なぐさめる', stem:'慰', split:3, gloss:'つらい人の心をやわらげる'},
    {r:'うるおう', stem:'潤', split:3, gloss:'水気をふくむ・恵まれる'},
    {r:'なめらか', stem:'滑', split:2, gloss:'つるつるしている'},
    {r:'おだやか', stem:'穏', split:2, gloss:'静かで落ち着いている'},
    {r:'あぶない', stem:'危', split:2, gloss:'あぶない'},
    {r:'うらむ', stem:'恨', split:2, gloss:'にくく思う気持ちをもち続ける'},
    {r:'うながす', stem:'促', split:3, gloss:'早くするように仕向ける'},
    {r:'にくらしい', stem:'憎', split:2, gloss:'にくいと感じる'},
    {r:'なまける', stem:'怠', split:2, gloss:'するべきことをしない'},
    {r:'あざやか', stem:'鮮', split:2, gloss:'色や技がはっきり見事だ'},
    {r:'あわただしい', stem:'慌', split:2, gloss:'せわしなく落ち着かない'},
    {r:'さそう', stem:'誘', split:2, gloss:'いっしょにするように勧める'},
    {r:'うれえる', stem:'憂', split:2, gloss:'心配する'},
    {r:'しずまる', stem:'鎮', split:2, gloss:'さわぎや痛みがおさまる'},
    {r:'つらぬく', stem:'貫', split:3, gloss:'最後までやりとおす・つきとおす'},
    {r:'したう', stem:'慕', split:2, gloss:'恋しく思う・尊敬してあとを追う'},
    {r:'かえりみる', stem:'顧', split:3, gloss:'ふりかえって考える・気にかける'},
    {r:'とげる', stem:'遂', split:1, gloss:'やりとおして成しとげる'},
    {r:'かかげる', stem:'掲', split:2, gloss:'高くさし上げる・のせて示す'},
    {r:'たずさえる', stem:'携', split:3, gloss:'手に持つ・身につけて行く'},
    {r:'いこう', stem:'憩', split:2, gloss:'休んでくつろぐ'},
    {r:'かしこい', stem:'賢', split:3, gloss:'頭がよい'},
    {r:'おろす', stem:'卸', split:2, gloss:'問屋が小売店に品物を売りわたす'},
    {r:'もぐる', stem:'潜', split:2, gloss:'水中や物の下に入りこむ'},
    {r:'にくむ', stem:'憎', split:2, gloss:'いやだと思う・きらう'},
    {r:'おしむ', stem:'惜', split:1, gloss:'大切に思って手放したくない'},
    {r:'いやしい', stem:'卑', split:2, gloss:'品がなく下品だ'},
    {r:'うらめしい', stem:'恨', split:2, gloss:'うらみたい気持ちだ'},
    {r:'あわてる', stem:'慌', split:2, gloss:'うろたえて落ち着きを失う'},
  ],
  doon: [
    {read:'コウ', phrase:'◯外に出かける', ans:'郊', dis:['甲','孔','絞']},
    {read:'カン', phrase:'習◯を身につける', ans:'慣', dis:['肝','冠','勘']},
    {read:'ショウ', phrase:'機械が故◯する', ans:'障', dis:['焦','掌','鐘']},
    {read:'ソウ', phrase:'部屋を◯除する', ans:'掃', dis:['桑','双','葬']},
    {read:'チュウ', phrase:'駅前に◯車する', ans:'駐', dis:['鋳','抽','宙']},
    {read:'ボウ', phrase:'危険を◯止する', ans:'防', dis:['妨','某','膨']},
    {read:'コウ', phrase:'◯果的な学習法', ans:'効', dis:['坑','孔','硬']},
    {read:'カン', phrase:'新◯線に乗る', ans:'幹', dis:['刊','勧','巻']},
    {read:'セイ', phrase:'◯確に計算する', ans:'正', dis:['制','政','声']},
    {read:'セイ', phrase:'◯神を集中する', ans:'精', dis:['制','晴','声']},
    {read:'シ', phrase:'先生の◯示に従う', ans:'指', dis:['支','志','師']},
    {read:'シ', phrase:'町の医◯にみてもらう', ans:'師', dis:['士','氏','枝']},
    {read:'キ', phrase:'◯械を運転する', ans:'機', dis:['起','期','貴']},
    {read:'キ', phrase:'毎日◯録をつける', ans:'記', dis:['期','起','気']},
    {read:'コ', phrase:'◯人的な意見', ans:'個', dis:['固','湖','庫']},
    {read:'ソウ', phrase:'体◯の時間', ans:'操', dis:['想','層','僧']},
    {read:'ソウ', phrase:'◯合的に判断する', ans:'総', dis:['想','草','層']},
    {read:'トウ', phrase:'朝から◯校する', ans:'登', dis:['投','湯','頭']},
    {read:'ホウ', phrase:'新聞で情◯を得る', ans:'報', dis:['放','包','法']},
    {read:'ホウ', phrase:'先生の家を◯問する', ans:'訪', dis:['放','砲','縫']},
    {read:'ケイ', phrase:'貴重な◯験を積む', ans:'経', dis:['系','係','型']},
    {read:'サイ', phrase:'劇場で公演を◯開する', ans:'再', dis:['災','妻','採']},
    {read:'カイ', phrase:'機械を分◯する', ans:'解', dis:['会','回','階']},
    {read:'シン', phrase:'◯刻な問題', ans:'深', dis:['真','心','申']},
  ],
  shikibetsu: [
    {k:'誘', words:['誘導','勧誘','誘発']},
    {k:'賢', words:['賢明','賢人','賢者']},
    {k:'隔', words:['隔離','間隔','隔年']},
    {k:'慰', words:['慰霊','慰安','慰問']},
    {k:'潜', words:['潜水','潜入','潜在']},
    {k:'抑', words:['抑制','抑圧','抑揚']},
    {k:'促', words:['促進','催促','促成']},
    {k:'排', words:['排水','排除','排出']},
    {k:'掃', words:['掃除','清掃','一掃']},
    {k:'駐', words:['駐車','駐在','常駐']},
    {k:'免', words:['免除','免許','免税']},
    {k:'綱', words:['綱領','要綱','横綱']},
    {k:'陳', words:['陳列','陳述','陳情']},
    {k:'遂', words:['遂行','完遂','未遂']},
    {k:'双', words:['双方','双子','無双']},
    {k:'卓', words:['卓越','卓球','食卓']},
    {k:'掌', words:['掌握','車掌','合掌']},
    {k:'譲', words:['譲歩','譲渡','委譲']},
    {k:'慕', words:['慕情','敬慕','思慕']},
    {k:'阻', words:['阻止','阻害','険阻']},
    {k:'鎮', words:['鎮圧','鎮火','鎮静']},
    {k:'幽', words:['幽霊','幽閉','幽谷']},
    {k:'賊', words:['盗賊','海賊','山賊']},
    {k:'錠', words:['錠前','施錠','手錠']},
  ],
  goji: [
    {sent:'入学試険に合格する。', wrong:'険', correct:'験', read:'ケン', dis:['検','圏','権']},
    {sent:'絶対絶命のピンチを切りぬける。', wrong:'対', correct:'体', read:'タイ', dis:['隊','態','逮']},
    {sent:'彼は短刀直入に用件を話した。', wrong:'短', correct:'単', read:'タン', dis:['端','嘆','担']},
    {sent:'自我自賛ばかりで人の話を聞かない。', wrong:'我', correct:'画', read:'ガ', dis:['賀','雅','芽']},
    {sent:'会議は一同に会して行われた。', wrong:'同', correct:'堂', read:'ドウ', dis:['動','導','銅']},
    {sent:'大学の講議に出席する。', wrong:'議', correct:'義', read:'ギ', dis:['儀','犠','疑']},
    {sent:'温古知新の精神で学ぶ。', wrong:'古', correct:'故', read:'コ', dis:['固','個','庫']},
    {sent:'心気一転して勉強にはげむ。', wrong:'気', correct:'機', read:'キ', dis:['起','貴','帰']},
    {sent:'用意週到に計画を立てる。', wrong:'週', correct:'周', read:'シュウ', dis:['収','秀','襲']},
    {sent:'危機一発のところで助かった。', wrong:'発', correct:'髪', read:'ハツ', dis:['抜','伐','罰']},
    {sent:'五里夢中で出口をさがす。', wrong:'夢', correct:'霧', read:'ム', dis:['務','矛','無']},
    {sent:'大同小違はあるが賛成だ。', wrong:'違', correct:'異', read:'イ', dis:['移','遺','威']},
    {sent:'会社の意志決定に加わる。', wrong:'志', correct:'思', read:'シ', dis:['師','士','支']},
    {sent:'鉄棒などの機械体操が得意だ。', wrong:'機', correct:'器', read:'キ', dis:['基','寄','規']},
    {sent:'油断大適は禁物だ。', wrong:'適', correct:'敵', read:'テキ', dis:['滴','摘','笛']},
    {sent:'責任転化をしてはいけない。', wrong:'化', correct:'嫁', read:'カ', dis:['科','課','貨']},
  ],
  bushu: [
    {k:'詠', rad:'言', name:'ごんべん'},
    {k:'慰', rad:'心', name:'こころ'},
    {k:'炎', rad:'火', name:'ひ'},
    {k:'宴', rad:'宀', name:'うかんむり'},
    {k:'欧', rad:'欠', name:'あくび'},
    {k:'殴', rad:'殳', name:'るまた'},
    {k:'穏', rad:'禾', name:'のぎへん'},
    {k:'架', rad:'木', name:'き'},
    {k:'嫁', rad:'女', name:'おんなへん'},
    {k:'怪', rad:'忄', name:'りっしんべん'},
    {k:'該', rad:'言', name:'ごんべん'},
    {k:'掛', rad:'扌', name:'てへん'},
    {k:'貫', rad:'貝', name:'かい'},
    {k:'喚', rad:'口', name:'くちへん'},
    {k:'緩', rad:'糸', name:'いとへん'},
    {k:'軌', rad:'車', name:'くるまへん'},
    {k:'騎', rad:'馬', name:'うまへん'},
    {k:'菊', rad:'艹', name:'くさかんむり'},
    {k:'峡', rad:'山', name:'やまへん'},
    {k:'凝', rad:'冫', name:'にすい'},
    {k:'刑', rad:'刂', name:'りっとう'},
    {k:'掲', rad:'扌', name:'てへん'},
    {k:'鶏', rad:'鳥', name:'とり'},
    {k:'鯨', rad:'魚', name:'うおへん'},
    {k:'賢', rad:'貝', name:'かい'},
    {k:'弧', rad:'弓', name:'ゆみへん'},
    {k:'雇', rad:'隹', name:'ふるとり'},
    {k:'顧', rad:'頁', name:'おおがい'},
    {k:'孔', rad:'子', name:'こへん'},
    {k:'硬', rad:'石', name:'いしへん'},
    {k:'酵', rad:'酉', name:'とりへん'},
    {k:'恨', rad:'忄', name:'りっしんべん'},
    {k:'魂', rad:'鬼', name:'おに'},
    {k:'債', rad:'亻', name:'にんべん'},
    {k:'祉', rad:'礻', name:'しめすへん'},
    {k:'疾', rad:'疒', name:'やまいだれ'},
    {k:'赦', rad:'赤', name:'あか'},
    {k:'殊', rad:'歹', name:'がつへん'},
    {k:'遂', rad:'辶', name:'しんにょう'},
    {k:'髄', rad:'骨', name:'ほねへん'},
    {k:'籍', rad:'竹', name:'たけかんむり'},
    {k:'潜', rad:'氵', name:'さんずい'},
    {k:'掃', rad:'扌', name:'てへん'},
    {k:'賊', rad:'貝', name:'かい'},
    {k:'胎', rad:'月', name:'にくづき'},
    {k:'鍛', rad:'金', name:'かねへん'},
    {k:'窒', rad:'穴', name:'あなかんむり'},
    {k:'彫', rad:'彡', name:'さんづくり'},
    {k:'聴', rad:'耳', name:'みみへん'},
    {k:'帝', rad:'巾', name:'はば'},
    {k:'篤', rad:'竹', name:'たけかんむり'},
    {k:'豚', rad:'豕', name:'いのこ'},
    {k:'尿', rad:'尸', name:'しかばね'},
    {k:'婆', rad:'女', name:'おんな'},
    {k:'帆', rad:'巾', name:'はばへん'},
    {k:'蛮', rad:'虫', name:'むし'},
    {k:'碑', rad:'石', name:'いしへん'},
    {k:'赴', rad:'走', name:'そうにょう'},
    {k:'符', rad:'竹', name:'たけかんむり'},
    {k:'覆', rad:'襾', name:'おおいかんむり'},
    {k:'墳', rad:'土', name:'つちへん'},
    {k:'癖', rad:'疒', name:'やまいだれ'},
    {k:'簿', rad:'竹', name:'たけかんむり'},
    {k:'崩', rad:'山', name:'やまへん'},
    {k:'翻', rad:'羽', name:'はね'},
    {k:'魅', rad:'鬼', name:'おに'},
    {k:'幽', rad:'幺', name:'いとがしら'},
    {k:'擁', rad:'扌', name:'てへん'},
    {k:'裸', rad:'衤', name:'ころもへん'},
    {k:'零', rad:'雨', name:'あめかんむり'},
    {k:'廉', rad:'广', name:'まだれ'},
    {k:'炉', rad:'火', name:'ひへん'},
    {k:'楼', rad:'木', name:'きへん'},
    {k:'湾', rad:'氵', name:'さんずい'},
    {k:'哀', rad:'口', name:'くち'},
    {k:'悦', rad:'忄', name:'りっしんべん'},
    {k:'閲', rad:'門', name:'もんがまえ'},
    {k:'乙', rad:'乙', name:'おつ'},
    {k:'卸', rad:'卩', name:'ふしづくり'},
    {k:'佳', rad:'亻', name:'にんべん'},
    {k:'餓', rad:'飠', name:'しょくへん'},
    {k:'塊', rad:'土', name:'つちへん'},
    {k:'慨', rad:'忄', name:'りっしんべん'},
    {k:'概', rad:'木', name:'きへん'},
    {k:'滑', rad:'氵', name:'さんずい'},
    {k:'冠', rad:'冖', name:'わかんむり'},
    {k:'勘', rad:'力', name:'ちから'},
    {k:'換', rad:'扌', name:'てへん'},
    {k:'企', rad:'人', name:'ひとやね'},
    {k:'忌', rad:'心', name:'こころ'},
    {k:'棋', rad:'木', name:'きへん'},
    {k:'犠', rad:'牛', name:'うしへん'},
    {k:'吉', rad:'口', name:'くち'},
    {k:'喫', rad:'口', name:'くちへん'},
    {k:'虐', rad:'虍', name:'とらがしら'},
    {k:'緊', rad:'糸', name:'いと'},
    {k:'愚', rad:'心', name:'こころ'},
    {k:'契', rad:'大', name:'だい'},
    {k:'啓', rad:'口', name:'くち'},
    {k:'携', rad:'扌', name:'てへん'},
    {k:'娯', rad:'女', name:'おんなへん'},
    {k:'巧', rad:'工', name:'たくみ'},
    {k:'坑', rad:'土', name:'つちへん'},
    {k:'拘', rad:'扌', name:'てへん'},
    {k:'控', rad:'扌', name:'てへん'},
    {k:'慌', rad:'忄', name:'りっしんべん'},
    {k:'絞', rad:'糸', name:'いとへん'},
    {k:'紺', rad:'糸', name:'いとへん'},
    {k:'墾', rad:'土', name:'つち'},
    {k:'催', rad:'亻', name:'にんべん'},
    {k:'削', rad:'刂', name:'りっとう'},
    {k:'搾', rad:'扌', name:'てへん'},
    {k:'錯', rad:'金', name:'かねへん'},
    {k:'撮', rad:'扌', name:'てへん'},
    {k:'擦', rad:'扌', name:'てへん'},
    {k:'施', rad:'方', name:'ほうへん'},
    {k:'侍', rad:'亻', name:'にんべん'},
    {k:'慈', rad:'心', name:'こころ'},
    {k:'軸', rad:'車', name:'くるまへん'},
    {k:'湿', rad:'氵', name:'さんずい'},
    {k:'寿', rad:'寸', name:'すん'},
    {k:'潤', rad:'氵', name:'さんずい'},
    {k:'遵', rad:'辶', name:'しんにょう'},
    {k:'如', rad:'女', name:'おんなへん'},
    {k:'徐', rad:'彳', name:'ぎょうにんべん'},
    {k:'匠', rad:'匚', name:'はこがまえ'},
    {k:'昇', rad:'日', name:'ひ'},
    {k:'晶', rad:'日', name:'ひ'},
    {k:'鐘', rad:'金', name:'かねへん'},
    {k:'嬢', rad:'女', name:'おんなへん'},
    {k:'錠', rad:'金', name:'かねへん'},
    {k:'譲', rad:'言', name:'ごんべん'},
    {k:'辱', rad:'辰', name:'しんのたつ'},
    {k:'伸', rad:'亻', name:'にんべん'},
    {k:'審', rad:'宀', name:'うかんむり'},
    {k:'炊', rad:'火', name:'ひへん'},
    {k:'粋', rad:'米', name:'こめへん'},
    {k:'衰', rad:'衣', name:'ころも'},
    {k:'酔', rad:'酉', name:'とりへん'},
    {k:'穂', rad:'禾', name:'のぎへん'},
    {k:'牲', rad:'牛', name:'うしへん'},
    {k:'婿', rad:'女', name:'おんなへん'},
    {k:'請', rad:'言', name:'ごんべん'},
    {k:'惜', rad:'忄', name:'りっしんべん'},
    {k:'摂', rad:'扌', name:'てへん'},
    {k:'繕', rad:'糸', name:'いとへん'},
    {k:'措', rad:'扌', name:'てへん'},
    {k:'粗', rad:'米', name:'こめへん'},
    {k:'礎', rad:'石', name:'いしへん'},
    {k:'桑', rad:'木', name:'き'},
    {k:'葬', rad:'艹', name:'くさかんむり'},
    {k:'憎', rad:'忄', name:'りっしんべん'},
    {k:'促', rad:'亻', name:'にんべん'},
    {k:'怠', rad:'心', name:'こころ'},
    {k:'袋', rad:'衣', name:'ころも'},
    {k:'逮', rad:'辶', name:'しんにょう'},
    {k:'滞', rad:'氵', name:'さんずい'},
    {k:'択', rad:'扌', name:'てへん'},
    {k:'託', rad:'言', name:'ごんべん'},
    {k:'諾', rad:'言', name:'ごんべん'},
    {k:'奪', rad:'大', name:'だい'},
    {k:'胆', rad:'月', name:'にくづき'},
    {k:'壇', rad:'土', name:'つちへん'},
    {k:'稚', rad:'禾', name:'のぎへん'},
    {k:'抽', rad:'扌', name:'てへん'},
    {k:'鋳', rad:'金', name:'かねへん'},
    {k:'駐', rad:'馬', name:'うまへん'},
    {k:'超', rad:'走', name:'そうにょう'},
    {k:'鎮', rad:'金', name:'かねへん'},
    {k:'墜', rad:'土', name:'つち'},
    {k:'訂', rad:'言', name:'ごんべん'},
    {k:'締', rad:'糸', name:'いとへん'},
    {k:'哲', rad:'口', name:'くち'},
    {k:'塗', rad:'土', name:'つち'},
    {k:'凍', rad:'冫', name:'にすい'},
    {k:'痘', rad:'疒', name:'やまいだれ'},
    {k:'匿', rad:'匚', name:'はこがまえ'},
    {k:'粘', rad:'米', name:'こめへん'},
    {k:'排', rad:'扌', name:'てへん'},
    {k:'縛', rad:'糸', name:'いとへん'},
    {k:'伐', rad:'亻', name:'にんべん'},
    {k:'伴', rad:'亻', name:'にんべん'},
    {k:'畔', rad:'田', name:'たへん'},
    {k:'藩', rad:'艹', name:'くさかんむり'},
    {k:'泌', rad:'氵', name:'さんずい'},
    {k:'姫', rad:'女', name:'おんなへん'},
    {k:'漂', rad:'氵', name:'さんずい'},
    {k:'苗', rad:'艹', name:'くさかんむり'},
    {k:'封', rad:'寸', name:'すん'},
    {k:'伏', rad:'亻', name:'にんべん'},
    {k:'紛', rad:'糸', name:'いとへん'},
    {k:'慕', rad:'心', name:'したごころ'},
    {k:'芳', rad:'艹', name:'くさかんむり'},
    {k:'胞', rad:'月', name:'にくづき'},
    {k:'倣', rad:'亻', name:'にんべん'},
    {k:'飽', rad:'飠', name:'しょくへん'},
    {k:'縫', rad:'糸', name:'いとへん'},
    {k:'妨', rad:'女', name:'おんなへん'},
    {k:'房', rad:'戸', name:'とだれ'},
    {k:'膨', rad:'月', name:'にくづき'},
    {k:'謀', rad:'言', name:'ごんべん'},
    {k:'墨', rad:'土', name:'つち'},
    {k:'没', rad:'氵', name:'さんずい'},
    {k:'埋', rad:'土', name:'つちへん'},
    {k:'膜', rad:'月', name:'にくづき'},
    {k:'抑', rad:'扌', name:'てへん'},
    {k:'揚', rad:'扌', name:'てへん'},
    {k:'揺', rad:'扌', name:'てへん'},
    {k:'隆', rad:'阝', name:'こざとへん'},
    {k:'糧', rad:'米', name:'こめへん'},
    {k:'励', rad:'力', name:'ちから'},
    {k:'浪', rad:'氵', name:'さんずい'},
    {k:'漏', rad:'氵', name:'さんずい'},
    {k:'陳', rad:'阝', name:'こざとへん'},
  ],
};
if (typeof module !== 'undefined') { module.exports = { KANKEN3_CONTENT }; }
