// kanji-data.js — 小学1年生 配当漢字 全80字
// Source: MEXT 学年別漢字配当表 (小学校学習指導要領 別表), the official grade-1
// list of exactly 80 characters — transcribed and cross-checked against the
// documented count (16 rows × 5 columns = 80 exactly), not reconstructed from
// memory. on/kun readings are the officially taught 音訓 for grade 1; stroke
// counts as published; okurigana shown with a hyphen (e.g. おお-きい). This is
// a closed, official list — no textbook passage or wording is reproduced.
const KANJI1 = [
  {k:'一', on:['イチ','イツ'], kun:['ひと','ひと-つ'], strokes:1},
  {k:'右', on:['ウ','ユウ'], kun:['みぎ'], strokes:5},
  {k:'雨', on:['ウ'], kun:['あめ','あま'], strokes:8},
  {k:'円', on:['エン'], kun:['まる-い'], strokes:4},
  {k:'王', on:['オウ'], kun:[], strokes:4},
  {k:'音', on:['オン','イン'], kun:['おと','ね'], strokes:9},
  {k:'下', on:['カ','ゲ'], kun:['した','しも','さ-げる','さ-がる','くだ-る','お-りる'], strokes:3},
  {k:'火', on:['カ'], kun:['ひ','ほ'], strokes:4},
  {k:'花', on:['カ'], kun:['はな'], strokes:7},
  {k:'貝', on:[], kun:['かい'], strokes:7},
  {k:'学', on:['ガク'], kun:['まな-ぶ'], strokes:8},
  {k:'気', on:['キ','ケ'], kun:[], strokes:6},
  {k:'九', on:['キュウ','ク'], kun:['ここの','ここの-つ'], strokes:2},
  {k:'休', on:['キュウ'], kun:['やす-む','やす-まる','やす-める'], strokes:6},
  {k:'玉', on:['ギョク'], kun:['たま'], strokes:5},
  {k:'金', on:['キン','コン'], kun:['かね','かな'], strokes:8},
  {k:'空', on:['クウ'], kun:['そら','あ-く','あ-ける','から'], strokes:8},
  {k:'月', on:['ゲツ','ガツ'], kun:['つき'], strokes:4},
  {k:'犬', on:['ケン'], kun:['いぬ'], strokes:4},
  {k:'見', on:['ケン'], kun:['み-る','み-える','み-せる'], strokes:7},
  {k:'五', on:['ゴ'], kun:['いつ','いつ-つ'], strokes:4},
  {k:'口', on:['コウ','ク'], kun:['くち'], strokes:3},
  {k:'校', on:['コウ'], kun:[], strokes:10},
  {k:'左', on:['サ'], kun:['ひだり'], strokes:5},
  {k:'三', on:['サン'], kun:['み','み-つ','みっ-つ'], strokes:3},
  {k:'山', on:['サン'], kun:['やま'], strokes:3},
  {k:'子', on:['シ','ス'], kun:['こ'], strokes:3},
  {k:'四', on:['シ'], kun:['よ','よ-つ','よっ-つ','よん'], strokes:5},
  {k:'糸', on:['シ'], kun:['いと'], strokes:6},
  {k:'字', on:['ジ'], kun:['あざ'], strokes:6},
  {k:'耳', on:['ジ'], kun:['みみ'], strokes:6},
  {k:'七', on:['シチ'], kun:['なな','なな-つ','なの'], strokes:2},
  {k:'車', on:['シャ'], kun:['くるま'], strokes:7},
  {k:'手', on:['シュ'], kun:['て','た'], strokes:4},
  {k:'十', on:['ジュウ','ジッ'], kun:['とお','と'], strokes:2},
  {k:'出', on:['シュツ','スイ'], kun:['で-る','だ-す'], strokes:5},
  {k:'女', on:['ジョ','ニョ','ニョウ'], kun:['おんな','め'], strokes:3},
  {k:'小', on:['ショウ'], kun:['ちい-さい','こ','お'], strokes:3},
  {k:'上', on:['ジョウ','ショウ'], kun:['うえ','うわ','かみ','あ-げる','あ-がる','のぼ-る'], strokes:3},
  {k:'森', on:['シン'], kun:['もり'], strokes:12},
  {k:'人', on:['ジン','ニン'], kun:['ひと'], strokes:2},
  {k:'水', on:['スイ'], kun:['みず'], strokes:4},
  {k:'正', on:['セイ','ショウ'], kun:['ただ-しい','ただ-す','まさ'], strokes:5},
  {k:'生', on:['セイ','ショウ'], kun:['い-きる','う-まれる','は-える','なま','き'], strokes:5},
  {k:'青', on:['セイ','ショウ'], kun:['あお','あお-い'], strokes:8},
  {k:'夕', on:['セキ'], kun:['ゆう'], strokes:3},
  {k:'石', on:['セキ','シャク','コク'], kun:['いし'], strokes:5},
  {k:'赤', on:['セキ','シャク'], kun:['あか','あか-い'], strokes:7},
  {k:'千', on:['セン'], kun:['ち'], strokes:3},
  {k:'川', on:['セン'], kun:['かわ'], strokes:3},
  {k:'先', on:['セン'], kun:['さき'], strokes:6},
  {k:'早', on:['ソウ'], kun:['はや-い','はや-まる','はや-める'], strokes:6},
  {k:'草', on:['ソウ'], kun:['くさ'], strokes:9},
  {k:'足', on:['ソク'], kun:['あし','た-りる','た-る','た-す'], strokes:7},
  {k:'村', on:['ソン'], kun:['むら'], strokes:7},
  {k:'大', on:['ダイ','タイ'], kun:['おお','おお-きい'], strokes:3},
  {k:'男', on:['ダン','ナン'], kun:['おとこ'], strokes:7},
  {k:'竹', on:['チク'], kun:['たけ'], strokes:6},
  {k:'中', on:['チュウ','ジュウ'], kun:['なか'], strokes:4},
  {k:'虫', on:['チュウ'], kun:['むし'], strokes:6},
  {k:'町', on:['チョウ'], kun:['まち'], strokes:7},
  {k:'天', on:['テン'], kun:['あめ','あま'], strokes:4},
  {k:'田', on:['デン'], kun:['た'], strokes:5},
  {k:'土', on:['ド','ト'], kun:['つち'], strokes:3},
  {k:'二', on:['ニ'], kun:['ふた','ふた-つ'], strokes:2},
  {k:'日', on:['ニチ','ジツ'], kun:['ひ','か'], strokes:4},
  {k:'入', on:['ニュウ'], kun:['い-る','はい-る','い-れる'], strokes:2},
  {k:'年', on:['ネン'], kun:['とし'], strokes:6},
  {k:'白', on:['ハク','ビャク'], kun:['しろ','しろ-い','しら'], strokes:5},
  {k:'八', on:['ハチ'], kun:['や','や-つ','やっ-つ','よう'], strokes:2},
  {k:'百', on:['ヒャク'], kun:[], strokes:6},
  {k:'文', on:['ブン','モン'], kun:['ふみ'], strokes:4},
  {k:'木', on:['ボク','モク'], kun:['き','こ'], strokes:4},
  {k:'本', on:['ホン'], kun:['もと'], strokes:5},
  {k:'名', on:['メイ','ミョウ'], kun:['な'], strokes:6},
  {k:'目', on:['モク','ボク'], kun:['め','ま'], strokes:5},
  {k:'立', on:['リツ','リュウ'], kun:['た-つ','た-てる'], strokes:5},
  {k:'力', on:['リョク','リキ'], kun:['ちから'], strokes:2},
  {k:'林', on:['リン'], kun:['はやし'], strokes:8},
  {k:'六', on:['ロク'], kun:['む','む-つ','むっ-つ','むい'], strokes:4},
];
if (typeof module !== 'undefined') module.exports = KANJI1;
