// kanji-data.js — 小学6年生 配当漢字 全191字
// Source: 学年別漢字配当表 (小学校学習指導要領 別表, 2017年告示・2020年度／
// 令和2年度 完全施行版). The current grade-6 set is 191 characters — verified
// three ways, NOT reconstructed from memory:
//   1. Two independent references (ja.wikipedia「学年別漢字配当表」and
//      benricho.org 教育漢字) both list 191 for 第6学年.
//   2. Cross-checked against the officially documented per-grade totals of the
//      2020 revision (G1..G6 = 80/160/200/202/193/191, sum 1026).
//   3. Derived programmatically from KANJIDIC2 (kanjiapi.dev grade-6 = the
//      pre-2020 181-char set) by applying the exact 2020 delta — the 11 kanji
//      moved INTO grade 6 (胃 腸 恩 券 承 舌 銭 退 敵 俵 預) and the 1 moved OUT
//      (城 → grade 4): 181 − 1 + 11 = 191. The derived set matched the
//      Wikipedia list character-for-character.
// (Note: KANJIDIC2 still tags the 11 moved-in kanji with their pre-2020 grade,
// so a naive `grade-6` API pull yields the stale 181 — kanken5 uses that older
// KANJIDIC2 grade-6 set on purpose; kokugo6 needs the current curriculum set,
// hence the explicit delta above.)
//
// Grade 6 is the final elementary grade, so this list completes the full
// elementary 学年別漢字配当表 across all six grades — a real milestone, not
// just another module.
//
// Readings follow the KANJIDIC2 / kanjiapi convention (same as kanken5-data.js):
// the okurigana boundary is marked with「.」and a prefix/suffix position with
// 「-」. The generator strips both「.」and「-」before displaying or comparing a
// reading. Characters are listed in the official 配当表 (gojūon) order.
const KANJI6 = [
  {k:'胃', on:['イ'], kun:[], strokes:9},
  {k:'異', on:['イ'], kun:['け','こと','こと.なる'], strokes:11},
  {k:'遺', on:['イ','ユイ'], kun:['のこ.す'], strokes:15},
  {k:'域', on:['イキ'], kun:[], strokes:11},
  {k:'宇', on:['ウ'], kun:[], strokes:6},
  {k:'映', on:['エイ'], kun:['-ば.え','うつ.す','うつ.る','は.える'], strokes:9},
  {k:'延', on:['エン'], kun:['の.ばす','の.びる','の.べ','の.べる'], strokes:8},
  {k:'沿', on:['エン'], kun:['-ぞ.い','そ.う'], strokes:8},
  {k:'恩', on:['オン'], kun:[], strokes:10},
  {k:'我', on:['ガ'], kun:['わ','わ.が-','わが-','われ'], strokes:7},
  {k:'灰', on:['カイ'], kun:['はい'], strokes:6},
  {k:'拡', on:['カク','コウ'], kun:['ひろ.がる','ひろ.げる','ひろ.める'], strokes:8},
  {k:'革', on:['カク'], kun:['かわ'], strokes:9},
  {k:'閣', on:['カク'], kun:[], strokes:14},
  {k:'割', on:['カツ'], kun:['さ.く','わ.り','わ.る','わ.れる','わり'], strokes:12},
  {k:'株', on:['シュ'], kun:['かぶ'], strokes:10},
  {k:'干', on:['カン'], kun:['-ぼ.し','ひ.る','ほ.し-','ほ.す'], strokes:3},
  {k:'巻', on:['カン','ケン'], kun:['ま.き','ま.く','まき'], strokes:9},
  {k:'看', on:['カン'], kun:['み.る'], strokes:9},
  {k:'簡', on:['カン','ケン'], kun:['えら.ぶ','ふだ'], strokes:18},
  {k:'危', on:['キ'], kun:['あぶ.ない','あや.うい','あや.ぶむ'], strokes:6},
  {k:'机', on:['キ'], kun:['つくえ'], strokes:6},
  {k:'揮', on:['キ'], kun:['ふる.う'], strokes:12},
  {k:'貴', on:['キ'], kun:['たっと.い','たっと.ぶ','とうと.い','とうと.ぶ'], strokes:12},
  {k:'疑', on:['ギ'], kun:['うたが.う'], strokes:14},
  {k:'吸', on:['キュウ'], kun:['す.う'], strokes:6},
  {k:'供', on:['キョウ','ク','クウ','グ'], kun:['-ども','そな.える','とも'], strokes:8},
  {k:'胸', on:['キョウ'], kun:['むな-','むね'], strokes:10},
  {k:'郷', on:['キョウ','ゴウ'], kun:['さと'], strokes:11},
  {k:'勤', on:['キン','ゴン'], kun:['-づと.め','いそ.しむ','つと.まる','つと.める'], strokes:12},
  {k:'筋', on:['キン'], kun:['すじ'], strokes:12},
  {k:'系', on:['ケイ'], kun:[], strokes:7},
  {k:'敬', on:['キョウ','ケイ'], kun:['うやま.う'], strokes:12},
  {k:'警', on:['ケイ'], kun:['いまし.める'], strokes:19},
  {k:'劇', on:['ゲキ'], kun:[], strokes:15},
  {k:'激', on:['ゲキ'], kun:['はげ.しい'], strokes:16},
  {k:'穴', on:['ケツ'], kun:['あな'], strokes:5},
  {k:'券', on:['ケン'], kun:[], strokes:8},
  {k:'絹', on:['ケン'], kun:['きぬ'], strokes:13},
  {k:'権', on:['ケン','ゴン'], kun:['おもり','かり','はか.る'], strokes:15},
  {k:'憲', on:['ケン'], kun:[], strokes:16},
  {k:'源', on:['ゲン'], kun:['みなもと'], strokes:13},
  {k:'厳', on:['ゲン','ゴン'], kun:['いか.めしい','いつくし','おごそ.か','きび.しい'], strokes:17},
  {k:'己', on:['キ','コ'], kun:['おのれ','つちのと','な'], strokes:3},
  {k:'呼', on:['コ'], kun:['よ.ぶ'], strokes:8},
  {k:'誤', on:['ゴ'], kun:['-あやま.る','あやま.る'], strokes:14},
  {k:'后', on:['コウ','ゴ'], kun:['きさき'], strokes:6},
  {k:'孝', on:['キョウ','コウ'], kun:[], strokes:7},
  {k:'皇', on:['オウ','コウ'], kun:[], strokes:9},
  {k:'紅', on:['ク','コウ'], kun:['あか.い','くれない','べに'], strokes:9},
  {k:'降', on:['コウ','ゴ'], kun:['お.りる','お.ろす','くだ.す','くだ.る','ふ.り','ふ.る'], strokes:10},
  {k:'鋼', on:['コウ'], kun:['はがね'], strokes:16},
  {k:'刻', on:['コク'], kun:['きざ.み','きざ.む'], strokes:8},
  {k:'穀', on:['コク'], kun:[], strokes:14},
  {k:'骨', on:['コツ'], kun:['ほね'], strokes:10},
  {k:'困', on:['コン'], kun:['こま.る'], strokes:7},
  {k:'砂', on:['サ','シャ'], kun:['すな'], strokes:9},
  {k:'座', on:['ザ'], kun:['すわ.る'], strokes:10},
  {k:'済', on:['サイ','セイ'], kun:['-す.ます','-ず.み','-ずみ','す.ます','す.まない','す.む','すく.う','な.す','わた.る','わたし'], strokes:11},
  {k:'裁', on:['サイ'], kun:['さば.く','た.つ'], strokes:12},
  {k:'策', on:['サク'], kun:[], strokes:12},
  {k:'冊', on:['サク','サツ'], kun:['ふみ'], strokes:5},
  {k:'蚕', on:['サン','テン'], kun:['かいこ','こ'], strokes:10},
  {k:'至', on:['シ'], kun:['いた.る'], strokes:6},
  {k:'私', on:['シ'], kun:['わたくし','わたし'], strokes:7},
  {k:'姿', on:['シ'], kun:['すがた'], strokes:9},
  {k:'視', on:['シ'], kun:['み.る'], strokes:11},
  {k:'詞', on:['シ'], kun:['ことば'], strokes:12},
  {k:'誌', on:['シ'], kun:[], strokes:14},
  {k:'磁', on:['ジ'], kun:[], strokes:14},
  {k:'射', on:['シャ'], kun:['い.る','う.つ','さ.す'], strokes:10},
  {k:'捨', on:['シャ'], kun:['す.てる'], strokes:11},
  {k:'尺', on:['シャク','セキ'], kun:['さし'], strokes:4},
  {k:'若', on:['ジャク','ニャ','ニャク'], kun:['ごと.し','も.し','も.しくは','も.しくわ','わか-','わか.い'], strokes:8},
  {k:'樹', on:['ジュ'], kun:['き'], strokes:16},
  {k:'収', on:['シュウ'], kun:['おさ.まる','おさ.める'], strokes:4},
  {k:'宗', on:['シュウ','ソウ'], kun:['むね'], strokes:8},
  {k:'就', on:['シュウ','ジュ'], kun:['つ.く','つ.ける'], strokes:12},
  {k:'衆', on:['シュ','シュウ'], kun:['おお.い'], strokes:12},
  {k:'従', on:['ショウ','ジュ','ジュウ'], kun:['したが.う','したが.える','より'], strokes:10},
  {k:'縦', on:['ジュウ'], kun:['たて'], strokes:16},
  {k:'縮', on:['シュク'], kun:['ちぢ.まる','ちぢ.む','ちぢ.める','ちぢ.らす','ちぢ.れる'], strokes:17},
  {k:'熟', on:['ジュク'], kun:['う.れる'], strokes:15},
  {k:'純', on:['ジュン'], kun:[], strokes:10},
  {k:'処', on:['ショ'], kun:['-こ','お.る','ところ'], strokes:5},
  {k:'署', on:['ショ'], kun:[], strokes:13},
  {k:'諸', on:['ショ'], kun:['もろ'], strokes:15},
  {k:'除', on:['ジ','ジョ'], kun:['-よ.け','のぞ.く'], strokes:10},
  {k:'承', on:['ショウ','ジョウ'], kun:['う.ける','うけたまわ.る'], strokes:8},
  {k:'将', on:['ショウ','ソウ'], kun:['はた','ひきい.る','まさ','まさ.に','もって'], strokes:10},
  {k:'傷', on:['ショウ'], kun:['いた.む','いた.める','きず'], strokes:13},
  {k:'障', on:['ショウ'], kun:['さわ.る'], strokes:14},
  {k:'蒸', on:['ジョウ','セイ'], kun:['む.す','む.らす','む.れる'], strokes:13},
  {k:'針', on:['シン'], kun:['はり'], strokes:10},
  {k:'仁', on:['ジン','ニ','ニン'], kun:[], strokes:4},
  {k:'垂', on:['スイ'], kun:['-た.れ','た.らす','た.れ','た.れる','なんなんと.す'], strokes:8},
  {k:'推', on:['スイ'], kun:['お.す'], strokes:11},
  {k:'寸', on:['スン'], kun:[], strokes:3},
  {k:'盛', on:['ジョウ','セイ'], kun:['さか.る','さか.ん','も.る'], strokes:11},
  {k:'聖', on:['ショウ','セイ'], kun:['ひじり'], strokes:13},
  {k:'誠', on:['セイ'], kun:['まこと'], strokes:13},
  {k:'舌', on:['ゼツ'], kun:['した'], strokes:6},
  {k:'宣', on:['セン'], kun:['のたま.う'], strokes:9},
  {k:'専', on:['セン'], kun:['もっぱ.ら'], strokes:9},
  {k:'泉', on:['セン'], kun:['いずみ'], strokes:9},
  {k:'洗', on:['セン'], kun:['あら.う'], strokes:9},
  {k:'染', on:['セン'], kun:['し.み','し.みる','そ.まる','そ.める'], strokes:9},
  {k:'銭', on:['セン','ゼン'], kun:['すき','ぜに'], strokes:14},
  {k:'善', on:['ゼン'], kun:['い.い','よ.い','よ.く','よし.とする'], strokes:12},
  {k:'奏', on:['ソウ'], kun:['かな.でる'], strokes:9},
  {k:'窓', on:['ス','ソウ'], kun:['けむだし','てんまど','まど'], strokes:11},
  {k:'創', on:['ショウ','ソウ'], kun:['きず','けず.しける','つく.る','はじ.める'], strokes:12},
  {k:'装', on:['ショウ','ソウ'], kun:['よそお.い','よそお.う'], strokes:12},
  {k:'層', on:['ソウ'], kun:[], strokes:14},
  {k:'操', on:['サン','ソウ'], kun:['あやつ.る','みさお'], strokes:16},
  {k:'蔵', on:['ソウ','ゾウ'], kun:['おさ.める','かく.れる','くら'], strokes:15},
  {k:'臓', on:['ゾウ'], kun:['はらわた'], strokes:19},
  {k:'存', on:['ソン','ゾン'], kun:['あ.る','たも.つ','と.う','ながら.える'], strokes:6},
  {k:'尊', on:['ソン'], kun:['たっと.い','たっと.ぶ','とうと.い','とうと.ぶ'], strokes:12},
  {k:'退', on:['タイ'], kun:['しりぞ.く','しりぞ.ける','ど.く','の.く','の.ける','ひ.く'], strokes:9},
  {k:'宅', on:['タク'], kun:[], strokes:6},
  {k:'担', on:['タン'], kun:['かつ.ぐ','にな.う'], strokes:8},
  {k:'探', on:['タン'], kun:['さが.す','さぐ.る'], strokes:11},
  {k:'誕', on:['タン'], kun:[], strokes:15},
  {k:'段', on:['タン','ダン'], kun:[], strokes:9},
  {k:'暖', on:['ダン','ノン'], kun:['あたた.か','あたた.かい','あたた.まる','あたた.める'], strokes:13},
  {k:'値', on:['チ'], kun:['あたい','ね'], strokes:10},
  {k:'宙', on:['チュウ'], kun:[], strokes:8},
  {k:'忠', on:['チュウ'], kun:[], strokes:8},
  {k:'著', on:['チャク','チョ'], kun:['あらわ.す','いちじる.しい'], strokes:11},
  {k:'庁', on:['チョウ','テイ'], kun:['やくしょ'], strokes:5},
  {k:'頂', on:['チョウ'], kun:['いただ.く','いただき'], strokes:11},
  {k:'腸', on:['チョウ'], kun:['はらわた','わた'], strokes:13},
  {k:'潮', on:['チョウ'], kun:['うしお','しお'], strokes:15},
  {k:'賃', on:['チン'], kun:[], strokes:13},
  {k:'痛', on:['ツウ'], kun:['いた.い','いた.ましい','いた.む','いた.める'], strokes:12},
  {k:'敵', on:['テキ'], kun:['あだ','かたき','かな.う'], strokes:15},
  {k:'展', on:['テン'], kun:[], strokes:10},
  {k:'討', on:['トウ'], kun:['う.つ'], strokes:10},
  {k:'党', on:['トウ'], kun:['なかま','むら'], strokes:10},
  {k:'糖', on:['トウ'], kun:[], strokes:16},
  {k:'届', on:['カイ'], kun:['-とど.け','とど.く','とど.ける'], strokes:8},
  {k:'難', on:['ナン'], kun:['-がた.い','-にく.い','かた.い','むずか.しい','むつか.しい','むづか.しい'], strokes:18},
  {k:'乳', on:['ニュウ'], kun:['ち','ちち'], strokes:8},
  {k:'認', on:['ニン'], kun:['したた.める','みと.める'], strokes:14},
  {k:'納', on:['トウ','ナ','ナッ','ナン','ノウ'], kun:['-おさ.める','おさ.まる','おさ.める'], strokes:10},
  {k:'脳', on:['ドウ','ノウ'], kun:['のうずる'], strokes:11},
  {k:'派', on:['ハ'], kun:[], strokes:9},
  {k:'拝', on:['ハイ'], kun:['おが.む','おろが.む'], strokes:8},
  {k:'背', on:['ハイ'], kun:['せ','せい','そむ.く','そむ.ける'], strokes:9},
  {k:'肺', on:['ハイ'], kun:[], strokes:9},
  {k:'俳', on:['ハイ'], kun:[], strokes:10},
  {k:'班', on:['ハン'], kun:[], strokes:10},
  {k:'晩', on:['バン'], kun:[], strokes:12},
  {k:'否', on:['ヒ'], kun:['いな','いや'], strokes:7},
  {k:'批', on:['ヒ'], kun:[], strokes:7},
  {k:'秘', on:['ヒ'], kun:['かく.す','ひ.める','ひそ.か'], strokes:10},
  {k:'俵', on:['ヒョウ'], kun:['たわら'], strokes:10},
  {k:'腹', on:['フク'], kun:['はら'], strokes:13},
  {k:'奮', on:['フン'], kun:['ふる.う'], strokes:16},
  {k:'並', on:['ヘイ','ホウ'], kun:['な.み','なみ','なら.びに','なら.ぶ','なら.べる'], strokes:8},
  {k:'陛', on:['ヘイ'], kun:[], strokes:10},
  {k:'閉', on:['ヘイ'], kun:['し.まる','し.める','た.てる','と.ざす','と.じる'], strokes:11},
  {k:'片', on:['ヘン'], kun:['かた','かた-'], strokes:4},
  {k:'補', on:['ホ'], kun:['おぎな.う'], strokes:12},
  {k:'暮', on:['ボ'], kun:['く.らす','く.れる'], strokes:14},
  {k:'宝', on:['ホウ'], kun:['たから'], strokes:8},
  {k:'訪', on:['ホウ'], kun:['おとず.れる','たず.ねる','と.う'], strokes:11},
  {k:'亡', on:['ボウ','モウ'], kun:['な.い','な.き-','ほろ.びる','ほろ.ぶ','ほろ.ぼす'], strokes:3},
  {k:'忘', on:['ボウ'], kun:['わす.れる'], strokes:7},
  {k:'棒', on:['ボウ'], kun:[], strokes:12},
  {k:'枚', on:['バイ','マイ'], kun:[], strokes:8},
  {k:'幕', on:['バク','マク'], kun:['とばり'], strokes:13},
  {k:'密', on:['ミツ'], kun:['ひそ.か'], strokes:11},
  {k:'盟', on:['メイ'], kun:[], strokes:13},
  {k:'模', on:['ボ','モ'], kun:[], strokes:14},
  {k:'訳', on:['ヤク'], kun:['わけ'], strokes:11},
  {k:'郵', on:['ユウ'], kun:[], strokes:11},
  {k:'優', on:['ウ','ユウ'], kun:['すぐ.れる','まさ.る','やさ.しい'], strokes:17},
  {k:'預', on:['ヨ'], kun:['あず.かる','あず.ける'], strokes:13},
  {k:'幼', on:['ヨウ'], kun:['おさな.い'], strokes:5},
  {k:'欲', on:['ヨク'], kun:['ほ.しい','ほっ.する'], strokes:11},
  {k:'翌', on:['ヨク'], kun:[], strokes:11},
  {k:'乱', on:['ラン','ロン'], kun:['おさ.める','みだ','みだ.す','みだ.る','みだ.れる','わた.る'], strokes:7},
  {k:'卵', on:['ラン'], kun:['たまご'], strokes:7},
  {k:'覧', on:['ラン'], kun:['み.る'], strokes:17},
  {k:'裏', on:['リ'], kun:['うら'], strokes:13},
  {k:'律', on:['リチ','リツ','レツ'], kun:[], strokes:9},
  {k:'臨', on:['リン'], kun:['のぞ.む'], strokes:18},
  {k:'朗', on:['ロウ'], kun:['あき.らか','ほが.らか'], strokes:10},
  {k:'論', on:['ロン'], kun:['あげつら.う'], strokes:15},
];
if (typeof module !== 'undefined') module.exports = KANJI6;
